### ISSUE TITLE
nevalau on Reddit has RBAC issue

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#103]
![image](https://user-images.githubusercontent.com/98695/52658312-9413f080-2eaf-11e9-827f-9fa3adfef6bc.png)

`2019-02-12T09:00:06.663145281Z time="2019-02-12T09:00:06Z" level=warning msg="DaemonSetCheckerError determining which node was unschedulable. Retrying.nodes is forbidden: User \"system:serviceaccount:kuberhealthy:kuberhealthy\" cannot list resource \"nodes\" in API group \"\" at the cluster scope"`

**Steps To Reproduce**
Install the helm chart

**Expected behavior**
The helm chart installs and everything works

**Comment by tommy-dk** [comment]
I am seeing the same error on an Azure AKS cluster.

**Comment by nevalla** [comment]
I left the original comment on reddit. I'm using [Kontena Pharos](https://github.com/kontena/pharos-cluster) to provision the cluster with RBAC enabled.

The issue might be that Helm chart will create a cluster role, but it allows only to list `pods`, `namespaces`, and `componentstatuses`. So service account doesn't have rights to list nodes. https://github.com/helm/charts/blob/master/stable/kuberhealthy/templates/clusterrole.yaml

**Comment by integrii** [comment]
Ah, we haven't run this on Kubernetes 1.13 yet... Looks like listing nodes requires additional RBAC permissions.

@nevalla if you edit `clusterrole.yaml` and add `- nodes` to the `resoruces` list, does it fix the issue?

**Comment by tommy-dk** [comment]
> Ah, we haven't run this on Kubernetes 1.13 yet... Looks like listing nodes requires additional RBAC permissions.
> 
> @nevalla if you edit `clusterrole.yaml` and add `- nodes` to the `resoruces` list, does it fix the issue?

This fixed the issue for me on AKS v 1.12.

**Comment by nevalla** [comment]
Yes I can confirm too:

<img width="1486" alt="screenshot 2019-02-14 at 12 40 04" src="https://user-images.githubusercontent.com/455844/52781670-ccedca00-3055-11e9-88dd-4c31f0690fa6.png">

I think this is related more to RBAC in general, not to Kubernetes version.

**Comment by integrii** [comment]
Glad to hear this works!  I suppose Kuberhealthy has now been tested on 1.13 :-)

Before we close this issue, we need to edit the helm chart to add this additional permission.

**Comment by davidkarlsen** [comment]
I have a PR ready with a fix for this + a fix for security context:
https://github.com/davidkarlsen/charts/tree/khealthcontext

**Comment by integrii** [comment]
Thanks to both of you!  Closing this out now.

**Comment by integrii** [comment]
I just remembered that this needs added to the deployment.yml file in this repo.  Leaving myself a reminder here to do this...
