### ISSUE TITLE
Missing env variable: MY_POD_NAME

### ISSUE THREAD

**Issue by johscheuer** [Comcast/kuberhealthy#108]
**Describe the bug**

I used https://github.com/Comcast/kuberhealthy/blob/master/deploy/kuberhealthy.yaml to deploy  kuberhealthy in my Kubernetes cluster. The pod always complain with the following error:

```bash
time="2019-02-13T12:57:40Z" level=error msg="Could not retreive Environment variable, or it had no content. MY_POD_NAME"
time="2019-02-13T12:57:50Z" level=error msg="Could not retreive Environment variable, or it had no content. MY_POD_NAME"
time="2019-02-13T12:57:50Z" level=error msg="Could not retreive Environment variable, or it had no content. MY_POD_NAME"
time="2019-02-13T12:58:00Z" level=error msg="Could not retreive Environment variable, or it had no content. MY_POD_NAME"
time="2019-02-13T12:58:00Z" level=error msg="Could not retreive Environment variable, or it had no content. MY_POD_NAME"
```

**Steps To Reproduce**
- `kubectl apply -f https://github.com/Comcast/kuberhealthy/blob/master/deploy/kuberhealthy.yaml`

**Expected behavior**
The kuberhealhy deployment should work out of the box. The issue came probably with this commit: https://github.com/Comcast/kuberhealthy/commit/dc768f88e0e8d17ef766ebe276bb5ad58141a37d the manifest should point to a container tag that supports the new env variable (or sets the old one). 

**Versions**
 - Cluster OS: COS on GKE
 - Kubernetes Version: `v1.11.6-gke.3`
 - Kuberhealthy Release or build [e.g. 0.1.5 or 235]

**Additional context**
Changing the version from `0.1.1` to `1.0.0` works: https://quay.io/repository/comcast/kuberhealthy?tab=tags

**Comment by integrii** [comment]
Thanks for taking the time to make an issue on this.  Looks like once we started focusing on the [helm chart](https://github.com/helm/charts/tree/master/stable/kuberhealthy), we stopped keeping that deploy yaml up to date.  I will bring that into sync so this won't be an issue, then you should be able to try again.  Sorry!  Fixing right now...

**Comment by integrii** [comment]
Closing for now. Let us know if you have other issues.
