### ISSUE TITLE
Add slack channel to documentation

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#113]
We should add #kuberhealthy from the Kubernetes slack to the readme.  Perhaps a badge that you can click to join?

**Comment by davidkarlsen** [comment]
Seems like invites is currently unavailable: http://slack.k8s.io/

**Comment by integrii** [comment]
Whoa. I feel like I read that this happened weeks ago. Maybe the kubernetes slack is locked down now?

**Comment by davidkarlsen** [comment]
It's back now - PR added.

**Comment by integrii** [comment]
I am making some more changes, then I will merge this to the branch where the github site lives.
