### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by davidkarlsen** [Comcast/kuberhealthy#114]
**Describe the bug**
POD fails with:
```
kubectl -n kuberhealthy logs kuberhealthy-7868b9cd7b-6s42h 
time="2019-02-19T18:09:48Z" level=info msg="Startup Arguments: [/app/kuberhealthy]"
time="2019-02-19T18:09:48Z" level=info msg="Starting web services on port :8080"
time="2019-02-19T18:09:48Z" level=info msg="I am now master. Starting checks."
time="2019-02-19T18:09:48Z" level=info msg="Became master. Starting checks."
time="2019-02-19T18:09:48Z" level=info msg="Running check: PodStatusChecker namespace kube-system"
time="2019-02-19T18:09:48Z" level=info msg="Running check: DaemonSetChecker"
time="2019-02-19T18:09:48Z" level=info msg="Running check: PodRestartChecker namespace kube-system"
time="2019-02-19T18:09:48Z" level=info msg="Running check: ComponentStatusChecker"
time="2019-02-19T18:09:48Z" level=info msg="Setting state of check ComponentStatusChecker to true []"
time="2019-02-19T18:09:48Z" level=info msg="Searching for unique taints on the cluster."
time="2019-02-19T18:09:48Z" level=info msg="Found taints to tolerate: [{dedicated  infra NoSchedule <nil>}]"
time="2019-02-19T18:09:48Z" level=info msg="Generating daemon set kubernetes spec."
time="2019-02-19T18:09:48Z" level=info msg="Deploying daemon set with tolerations:  [{dedicated  infra NoSchedule <nil>}]"
time="2019-02-19T18:09:48Z" level=info msg="DaemonSetChecker removing 0 daemonset pods"
time="2019-02-19T18:09:48Z" level=info msg="DaemonSetChecker removing daemonset"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xf77cb1]

goroutine 39 [running]:
main.(*Kuberhealthy).setCheckExecutionError(0xc00025e6e0, 0x11b0b5a, 0x10, 0x0, 0x0)
        /go/src/github.com/Comcast/kuberhealthy/cmd/kuberhealthy/kuberhealthy.go:63 +0x211
main.(*Kuberhealthy).runCheck(0xc00025e6e0, 0xc0003dc0e0, 0x1302f20, 0xc000247000)
        /go/src/github.com/Comcast/kuberhealthy/cmd/kuberhealthy/kuberhealthy.go:242 +0x366
created by main.(*Kuberhealthy).StartChecks
        /go/src/github.com/Comcast/kuberhealthy/cmd/kuberhealthy/kuberhealthy.go:123 +0xf9
```

**Steps To Reproduce**
- install with the helm chart

**Expected behavior**
Should run without failure with default settings.

**Screenshots**
N/A

**Versions**
 - Cluster OS: RHEL 7.6
 - Kubernetes Version: v1.12.4+icp-ee
 - Kuberhealthy: 1.0.0

**Additional context**

**Comment by integrii** [comment]
Thanks for reporting this!

**Comment by davidkarlsen** [comment]
Is there any possible workaround?

**Comment by lolimjake** [comment]
I'm going to investigate this today/this weekend and fix it/let you know.

**Comment by lolimjake** [comment]
Is your kuberhealthy creating any daemon set pods at all, it doesn't appear to be from the logs.  A successful deploy looks like this:

`time="2019-02-22T20:48:58Z" level=info msg="Searching for unique taints on the cluster."
time="2019-02-22T20:48:58Z" level=info msg="Found taints to tolerate: [{dedicated  dfh NoSchedule <nil>} {node-role.kubernetes.io/master   NoSchedule <nil>}]"
time="2019-02-22T20:48:58Z" level=info msg="Generating daemon set kubernetes spec."
time="2019-02-22T20:48:58Z" level=info msg="Deploying daemon set with tolerations:  [{node-role.kubernetes.io/master   NoSchedule <nil>}]"
time="2019-02-22T20:48:59Z" level=info msg="DaemonSetChecker Daemonset check waiting for 27 pods to come up on nodes [<list of nodes here>]"
time="2019-02-22T20:49:01Z" level=info msg="All daemonset pods have been ready for 1 / 5 seconds."
time="2019-02-22T20:49:02Z" level=info msg="All daemonset pods have been ready for 2 / 5 seconds."
time="2019-02-22T20:49:03Z" level=info msg="All daemonset pods have been ready for 3 / 5 seconds."
time="2019-02-22T20:49:04Z" level=info msg="All daemonset pods have been ready for 4 / 5 seconds."
time="2019-02-22T20:49:05Z" level=info msg="All daemonset pods have been ready for 5 / 5 seconds."
time="2019-02-22T20:49:05Z" level=info msg="DaemonSetChecker Daemonset daemonset-test-kuberhealthy-565ffb89f-5blrq-1549985617 done deploying pods."
time="2019-02-22T20:49:05Z" level=info msg="DaemonSetChecker removing 28 daemonset pods"
time="2019-02-22T20:49:05Z" level=info msg="DaemonSetChecker removing daemonset"
time="2019-02-22T20:49:05Z" level=info msg="DaemonSetChecker removing daemonset pods"
time="2019-02-22T20:49:07Z" level=info msg="DaemonSetChecker using LabelSelector: app=daemonset-test-kuberhealthy-565ffb89f-5blrq-1549985617,source=kuberhealthy"
time="2019-02-22T20:49:07Z" level=info msg="DaemonSetChecker Daemonset check waiting for 28 pods to delete"
`

And then it goes on to loop through waiting for the pods to delete.

**Comment by davidkarlsen** [comment]
It creates two, but the "primary" one goes into a crashloop:
```
kuberhealthy-7868b9cd7b-6s42h   0/1     CrashLoopBackOff   899        3d4h
kuberhealthy-7868b9cd7b-w4rtx   1/1     Running            0          3d4h
```

**Comment by lolimjake** [comment]
That's one of the kuberhealthy master/slave pods.  Kuberhealthy will create a short lived daemon set which it appears to be failing to do. I suspect the failure to create the DS has to do with differences between standard Kube and OpenShift, though I'm still investigating and want to confirm that.

**Comment by davidkarlsen** [comment]
It's not OpenShift - but ICP: https://www.ibm.com/support/knowledgecenter/en/SSBS6K_3.1.2
Maybe my PodSecurityPolicy is too strict? But it would be good to fail with a more informative message.

**Comment by lolimjake** [comment]
I agree, even if it is pod security causing the DS deployment failure we should have better error handling and definitely not panic.

I've just pushed a few changes to the unstable tag, could you please update your Kuberhealthy deployment's tag to quay.io/comcast/kuberhealthy:unstable and report back.  

I added better logging around the DS checks and teardown and fixed what may be the bug causing your issue.  Commit changes found here: https://github.com/Comcast/kuberhealthy/compare/error-set-nil-fix

**Comment by davidkarlsen** [comment]
Great - now the error is revealed:
```
time="2019-02-24T10:14:05Z" level=info msg="Deploying daemon set with tolerations:  [{dedicated  infra NoSchedule <nil>}]"
time="2019-02-24T10:14:05Z" level=error msg="Failed to create daemon set:Internal error occurred: admission webhook \"trust.hooks.securityenforcement.admission.cloud.ibm.com\" denied the request: \nDeny \"gcr.io/google_containers/pause:0.8.0\", no matching repositories in ClusterImagePolicy and no ImagePolicies in the \"kuberhealthy\" namespace"
time="2019-02-24T10:14:05Z" level=error msg="Something went wrong with daemonset deployment, cleaning things up..."
time="2019-02-24T10:14:05Z" level=info msg="Setting state of check PodRestartChecker namespace kube-system to true []"
time="2019-02-24T10:14:05Z" level=info msg="DaemonSetChecker removing 0 daemonset pods"
time="2019-02-24T10:14:05Z" level=info msg="DaemonSetChecker removing daemonset"
time="2019-02-24T10:14:05Z" level=error msg="Failed to delete daemonset:daemonsets.extensions \"daemonset-test-kuberhealthy-f9df76c-jjj2x-1551001435\" not found"
time="2019-02-24T10:14:05Z" level=info msg="Setting state of check PodStatusChecker namespace kube-system to true []"
time="2019-02-24T10:14:05Z" level=error msg="Error running check: DaemonSetChecker Internal error occurred: admission webhook \"trust.hooks.securityenforcement.admission.cloud.ibm.com\" denied the request: \nDeny \"gcr.io/google_containers/pause:0.8.0\", no matching repositories in ClusterImagePolicy and no ImagePolicies in the \"kuberhealthy\" namespace"
```
we have to go through a proxy to reach images - can this be configured  in any way?

**Comment by lolimjake** [comment]
Great, looks like the panic is fixed!  

Its possible to make the daemon set image configurable - is the idea that you would upload the pause container to your internal repo and point the daemon set configuration at that internal repo instead?  If that is the case, a configurable DS image seems like a reasonable feature request to me.

**Comment by davidkarlsen** [comment]
Yes - that's what I need - actually it will be pulled on demand in a write-through manner - so what I need is to configure the full url of any images used by kuberhealthy at deployment time through the chart.

**Comment by davidkarlsen** [comment]
Should we closed this one as fixed and create a new issue for the configurability?

**Comment by lolimjake** [comment]
I was just going to suggest opening up a feature request for that part.  If you could make a feature request referencing this bug I'll take a look at the code.  I should have something for you to test out later tomorrow.

**Comment by davidkarlsen** [comment]
Closing as the actual panic reported was fixed.
