### ISSUE TITLE
[Helm] Prometheus scrape annotations on Service

### ISSUE THREAD

**Issue by logicfox** [Comcast/kuberhealthy#119]
**Describe the bug**
When Prometheus scraping is enabled from the values, the Prometheus scrape annotations are applied on the service. This would mean that the metrics are scraped from only one pod at any given time, and the request round-robins every time the <service>/metrics endpoint is scraped. 

**Steps To Reproduce**
Enable prometheus and scrape the endpoint

**Expected behavior**
Every pod is scraped for metrics

**Comment by davidkarlsen** [comment]
Fixed in https://github.com/helm/charts/pull/11651 which is being merged to master - this issue can be closed.

**Comment by davidkarlsen** [comment]
Usually prometheus is setup to find the endpoints behind the service and scrape all of them.
I have a "kubernetes-service-endpoints" job which does this.

**Comment by davidkarlsen** [comment]
See https://github.com/helm/charts/compare/master...davidkarlsen:fixKuberHealthyPorts?expand=1 which fixes this.
The two containers now show up with healthy state in my /prometheus/targets now.

**Comment by davidkarlsen** [comment]
This issue can be closed

**Comment by lolimjake** [comment]
Thanks @davidkarlsen!  @logicfox your change has been merged into the helm chart, going to mark this issue as closed, thanks for the contribution!
