### ISSUE TITLE
unable to see that kuberhealthy stats are coming to prometheus

### ISSUE THREAD

**Issue by immusk** [Comcast/kuberhealthy#129]
I have pulled the code from
https://github.com/helm/charts/tree/master/stable/kuberhealthy

deployed the helm chart using 
helm install stable/kuberhealthy --set prometheus.enabled=true

I have verified the prometheus labels too, everything looks good I am able to runt he curl and get the stats, but

when I try to see these stats on prometheus, I noticed that they are not getting pushed.
are there any other changes that I need to do ?

can someone please help here

**Comment by ihoegen** [comment]
@immusk which type of prometheus are you using?

The operator or the scraper?

**Comment by immusk** [comment]
@ihoegen apologies for late reply
I am using scrape

> prometheus.io/scrape: "true"

**Comment by ihoegen** [comment]
@immusk I haven't personally tested using scrape, only operator. I'll give it a try sometime this week

**Comment by integrii** [comment]
@ihoegen chart approved!

**Comment by immusk** [comment]
Thanks @ihoegen its is working now, now I am able to see the kuberhealthy stats coming to prometheus
