### ISSUE TITLE
How to add multiple namespaces for kuberhealthy

### ISSUE THREAD

**Issue by immusk** [Comcast/kuberhealthy#130]
Hi Team,

By default, kuberhealthy checks only for kube-system namespace
can you help me how and where to add multiple namespaces
if possible can you give a simple example how and where to add multiple namespaces or all namespaces.

**Comment by immusk** [comment]
I found it, how to give multiple namespaces

**Comment by saokar** [comment]
@immusk  Can you share how you made this work?

**Comment by immusk** [comment]
@saokar 
you can give multiple namespaces in values.yaml file
`
deployment:
  replicas: 2
  maxSurge: 0
  maxUnavailable: 1
  imagePullPolicy: IfNotPresent
  podAnnotations: {}
  command:
  - /app/kuberhealthy  
  # use this to override location of the test-image, see: https://github.com/Comcast/kuberhealthy/blob/master/docs/FLAGS.md
  args:
  - --podCheckNamespaces=namespace1,namespace2,namespace3
`

**Comment by integrii** [comment]
Ah yes, this would definitely case the pod restart checker to target multiple namespaces!
