### ISSUE TITLE
terminationGracePeriodSeconds can not be exposed in the pod spec as an env var

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#138]
We can not actually expose `terminationGracePeriodSeconds` to the pod.  :-( . 

We need to pull this out of the spec files (and helm chart if it was added there).

```
The Deployment "kuberhealthy" is invalid: spec.template.spec.containers[0].env[2].valueFrom.fieldRef.fieldPath: Invalid value: "spec.terminationGracePeriodSeconds": error converting fieldPath: field label not supported: spec.terminationGracePeriodSeconds
```

https://github.com/kubernetes/kubernetes/issues/50032

Apparently this is not supported by Kubernetes yet :-(

**Comment by lolimjake** [comment]
Reverted ⭕️
