### ISSUE TITLE
Allow for custom user checks

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#143]
Kuberhealthy could be turned into a great platform for users to easily write synthetic checks that include all the features Kuberhealthy provides today including metrics support and check lifecycle management.  It would be great if users could use some kind of SDK to build their own check container.  This would make Kuberhealthy a great facilitator for writing synthetic checks for any application.

I propose that a few elements of Kuberhealthy be created:

- A new check type that executes a job or daemonset, tracks it to completion, and shows the results in the usual prometheus and dashboard interfaces
- A new CRD that represents a "custom check" and the settings the custom check should use
    - check timeout
    - container URL
    - always/never pull container
    - kuberhealthy check status reporting URL
    - environment variables the pod should have applied
- A gRPC custom check status reporting handler so that checks can report status after running
- An SDK for users to easily develop checks of their own in any language.  Include application framework templates for several popular ones
 
The general flow of these custom checks would be:

- Kuberhealthy custom check CRD is created
- Kuberhealthy operator loads settings from CRD
- Kuberhealthy spawns job with check and manages a timeout
- Check runs and reports in to kuberhealthy status handler endpoint with gRPC
- Kuberhealthy shows most recent status of custom check alongside other checks on the prometheus endpoint and JSON status endpoint

**Comment by ihoegen-isp** [comment]
Approved

**Comment by ihoegen** [comment]
Approved. The sdk could either live in this project, or in a Kuberhealthy SDK repo

**Comment by integrii** [comment]
@lolimjake and I had a good design discussion for this today.  It breaks down into a few parts:

- [ ] A new check will be created that manages the lifecycle of a pod from end to end
- [ ] A new endpoint will be created that receives status updates from running pods and writes to the state CRD
- [ ] The status endpoint will drop any requests from pods that are not in its pod name whitelist
- [ ] A new CRD will be created that defines external checks, which image they run, how often, and what the timeouts are

**Comment by integrii** [comment]
Work on this continues in the 2.0.0 branch

**Comment by integrii** [comment]
This is working as a prototype in the 2.0.0 branch.  Let's switch to filing bugs.  Closing!
