### ISSUE TITLE
Bad/unused environment variables in default deploy specs

### ISSUE THREAD

**Issue by ihoegen** [Comcast/kuberhealthy#163]
**Describe the bug**
The deploy specs in the repo, *not* in the helm chart, contain these environment variables:
```
          - name: COMPONENT_STATUS_CHECK
            value: true
          - name: DAEMON_SET_CHECK
            value: true
          - name: DNS_STATUS_CHECK
            value: true
          - name: POD_RESTARTS_CHECK
            value: true
          - name: POD_STATUS_CHECK
            value: true
```
which aren't used anywhere in the code, and are invalid because the value must be a string. This causes installation to fail on the deployment. 
**Steps To Reproduce**
`kubectl apply -f deploy/kuberhealthy-and-prometheus.yaml`
**Expected behavior**
Kuberhealthy to install with no errors

**Comment by integrii** [comment]
https://github.com/Comcast/kuberhealthy/pull/164

**Comment by integrii** [comment]
These are now fixed up and/or working.
