### ISSUE TITLE
Error during helm install

### ISSUE THREAD

**Issue by saokar** [Comcast/kuberhealthy#180]
Trying to install kuberhealthy using helm. Cluster is running k8s 1.14

Getting the following error,

helm install stable/kuberhealthy
> Error: validation failed: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext, ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "imagePullPolicy" in io.k8s.api.core.v1.SecurityContext]

**Comment by integrii** [comment]
Just looking at this, it looks like there must be something wrong with the chart.  The spec path referenced does not contain the specified fields, as the error says.

Here is the spec reference for 1.14: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#securitycontext-v1-core

Looks like something is going wrong with the indents and this line: https://github.com/helm/charts/blob/master/stable/kuberhealthy/templates/deployment.yaml#L58
