### ISSUE TITLE
Rewrite Helm chart for Kuberhealthy 2 and Helm 3

### ISSUE THREAD

**Issue by jonnydawg** [Comcast/kuberhealthy#189]
**Describe the bug**
Helm3 runs into an error when trying to template the stable kuberhealthy chart. The issue seems to come from the customresourcedefinition.yaml

In the following examples `helm` calls Helm2 and `helm3` calls Helm3.

```
helm template stable/kuberhealthy/ > helm2-kh.yaml
helm3 template stable/kuberhealthy/ > helm3-kh.yaml                                                         
Error: apiVersion "apiextensions.k8s.io/v1beta1" in kuberhealthy/templates/customresourcedefinition.yaml is not available
```

**Steps To Reproduce**
- Have a [Helm3 release installed](https://github.com/helm/helm/releases).
- Have a copy of stable [Helm3 charts](https://github.com/helm/charts/tree/master/stable).
- Try to run Helm3 `template` subcommand on [kuberhealthy chart](https://github.com/helm/charts/tree/master/stable/kuberhealthy)

**Expected behavior**
I am expecting for Helm3 to render chart templates normally without any errors.

It seems the the error is coming from the CRD.yaml; however, the stable [external-dns](https://github.com/helm/charts/tree/master/stable/external-dns) also has a CRD.yaml template using the same "apiextensions.k8s.io/v1beta1" `apiVersion` and can be templated fine.

```
helm3 template stable/external-dns/ > helm3-ext-dns.yaml                                                    
helm3 template stable/kuberhealthy/ > helm3-kh.yaml                                                         
Error: apiVersion "apiextensions.k8s.io/v1beta1" in kuberhealthy/templates/customresourcedefinition.yaml is not available
```

**Screenshots**
![image](https://user-images.githubusercontent.com/12464614/64885711-a4dd3e00-d619-11e9-87ff-fa5cb514975e.png)

![image](https://user-images.githubusercontent.com/12464614/64886215-7b70e200-d61a-11e9-89eb-d8c1a5ebac53.png)

**Versions**
 - Kubernetes Client Version: 1.15.3
 - Kubernetes Version: 1.11.7
 - Stable Kuberhealthy Helm chart on [master branch](https://github.com/helm/charts/tree/master/stable/kuberhealthy)
 - Helm2 Version: 2.14.3
 - Helm3 Version: 3.0.0-beta.3

**Additional context**
Helm2 does not run into any errors when rendering templates for `stable/kuberhealthy` and `stable/external-dns`.
Helm3 does not run into any errors when rendering templates for `stable/external-dns`, but does when rendering for `stable/kuberhealthy`

**Comment by integrii** [comment]
As part of fixing this, we can probably bring our chart out of the `helm/charts/stable` repository and into our own.  Helm 3 has the [chart museum](https://chartmuseum.com/) these days.

**Comment by integrii** [comment]
we should just rewrite the helm chart for kuberhealthy 2 and helm 3

**Comment by integrii** [comment]
Replaced by #111
