### ISSUE TITLE
Kuberhealthy creates incorrect host name when posting externalcheckstatus when not in kuberhealthy namespace

### ISSUE THREAD

**Issue by joshulyne** [Comcast/kuberhealthy#196]
**Describe the bug**
When running kuberhealthy locally in the `default` namespace, the host name we try to report the success or failure of the kuberhealthy check defaults to the `kuberhealthy` namespace.

**Steps To Reproduce**
- Run kuberhealthy locally in `default` namespace or any namespace not `kuberhealthy`
- Run a kuberhealthy check 

**Expected behavior**
The success or failure report should be sent to `kuberhealthy.default.svc.cluster.local` instead of `kuberhealthy.kuberhealthy.svc.cluster.local`

**Screenshots**
```
time="2019-09-25T00:22:32Z" level=info msg="Error reporting success to Kuberhealthy servers: Post http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus: dial tcp: lookup kuberhealthy.kuberhealthy.svc.cluster.local: no such host"
```

**Comment by integrii** [comment]
This fix is pushed and available in the `quay.io/comcast/kuberhealthy:2.0.0alpha2` image.
