### ISSUE TITLE
Improve error handling for duration parsing

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#205]
When a khcheck check has an invalid duration or timeout set, we assume a default and move on.  See line 314 in `kuberhealthy.go`.

We should change this to set a `khstate` error if the fields fail to parse.  The check should _not_ be added to the list of configured checks in this case.

**Comment by integrii** [comment]
https://github.com/Comcast/kuberhealthy/blob/2.0.0/cmd/kuberhealthy/kuberhealthy.go#L314

**Comment by joshulyne** [comment]
https://github.com/Comcast/kuberhealthy/blob/2.0.0/cmd/kuberhealthy/kuberhealthy.go#L344

**Comment by integrii** [comment]
this was fixed at some point in our error handling improvements
