### ISSUE TITLE
Clean up KHStates when external checks are deleted 

### ISSUE THREAD

**Issue by joshulyne** [Comcast/kuberhealthy#215]
**Describe the bug**
When a `khcheck` is created, a `khstate` is also created to report the status of the external check. However, when the `khcheck` is deleted the `khstate` does not get cleaned up. This does not affect our kuberhealthy status page as deleted external check statuses are not displayed. 

I have also noticed that when you try and delete the `khstate` manually from the command line (after you've deleted the `khcheck`), the `khstate` pops back up due to a getCurrentState function in kuberhealthy.go that continuously fetches the check status. From the log output below it seems like the custom resource never gets fully deleted when you delete the `khcheck` which recreates the `khstate` pod every time you try to delete it. 

```
time="2019-10-08T02:27:36Z" level=debug msg="Getting status of check for web request to status page: kh-daemonset-check"
time="2019-10-08T02:27:36Z" level=debug msg="Checking existence of custom resource: kh-daemonset-check"
time="2019-10-08T02:27:36Z" level=debug msg="khstate custom resource found: kh-daemonset-check"
time="2019-10-08T02:27:36Z" level=debug msg="Retrieving khstate custom resource for: kh-daemonset-check"
time="2019-10-08T02:27:36Z" level=debug msg="Successfully retrieved khstate resource: kh-daemonset-check"
time="2019-10-08T02:27:36Z" level=debug msg="Output for kh-daemonset-check hidden from status page due to blank authoritative pod"
time="2019-10-08T02:27:39Z" level=info msg="kuberhealthy/kh-daemonset-check: [waiting for external checker pod to report in...]"
```

**Steps To Reproduce**
- Create an external check 
- Check that a `khstate` is also created
- Delete `khcheck`
- Observe that `khstate` remains

**Expected behavior**
When a `khcheck` is deleted, `khstate` should also be deleted.

**Versions**
 - Kuberhealthy 2.0.0

**Comment by joshulyne** [comment]
@integrii I believe this is fixed now? Since you added the fix for kuberhealthy to no longer have these checks when they're deleted

**Comment by integrii** [comment]
Thanks for the well described issue.  That really helps define the problem.

I do agree that we should have some pathway to clean up old `khstate` resources in the cluster.  What exactly that lifecycle looks like is up for suggestion.

I think it's either going to be that the `khstate` is deleted as soon as the `khcheck` is deleted, or it's going to be the case that we wait some period of time after the `khcheck` is deleted.  However, tracking the time since `khcheck` deletion could be hard (where do we put the last seen timestamp?).

**Comment by joshulyne** [comment]
@integrii pretty sure this is happening now, closing this issue!
