### ISSUE TITLE
Create an image pull test

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#221]
Sometimes upstream repositories go down.  It would be nice to have an alert for this because it could quickly turn into a production problem.  All we need to do is configure a `khcheck` that uses the example checker and an `imagePullPolicy` of `Always`.

Docker went down today and Kuberhealthy v2 showed errors in our test lab, but it would be nice to have a dedicated check for this.

**Comment by sladyn98** [comment]
Hello, I would like to take up this issue in order to get familiar with the codebase, could you help me begin?

**Comment by integrii** [comment]
Hey there @sladyn98!  We would love to have your contribution.  This check should be easy.  Here is what I am thinking:

- Create a checker pod that ALWAYS exits by calling `checkclient.ReportSuccess()`
- Create a check spec (khcheck yaml) that uses this new check image and has `imagePullPolicy` set to `Always`

I would create the check in the `cmd/` directory of this project (fork the repo so you have access).  You can use [this example check](https://github.com/Comcast/kuberhealthy/tree/master/cmd/test-external-check) as a starting point (just copy the entire directory to get started).

When it comes time to make the check official, just push your image somewhere public (like a free quay.io account) and make a PR to put it in the [check registry](https://github.com/Comcast/kuberhealthy/blob/master/docs/EXTERNAL_CHECKS_REGISTRY.md).

Here are the docs for making your own check: https://github.com/Comcast/kuberhealthy/blob/master/docs/EXTERNAL_CHECK_CREATION.md
