### ISSUE TITLE
Create an admission controller for khcheck resources

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#222]
I would like us to have the ability to validate `khcheck` resources  prior to them ending up in the API server.  When bad `khcheck` resources get into the API, bad things like this happen:

```
time="2019-10-15T21:48:04Z" level=error msg="Error loading external checks: khcheckcrd.KuberhealthyCheckList.Items: []khcheckcrd.KuberhealthyCheck: khcheckcrd.KuberhealthyCheck.Spec: khcheckcrd.CheckConfig.PodSpec: v1.PodSpec.Containers: []v1.Container: decode slice: expect [ or n, but found {, error found in #10 byte of ...|tainers\":{\"env\":[{\"n|..., bigger context ...|e-068948b715cc\"},\"spec\":{\"podSpec\":{\"containers\":{\"env\":[{\"name\":\"INFLUX_HOST\",\"value\":\"http://monit|..."
```

This also causes a lot of `InternalError` when watching for `khcheck` changes:
![image](https://user-images.githubusercontent.com/98695/66874373-c5255300-ef5f-11e9-8da6-baffbd5b1fa4.png)

We could implement a *redundant* admission controller and ship it along with Kuberhealthy.  This controller will validate the incoming pod spec to ensure that it properly can be converted to a `corev1.PodSpec`.

This is only valid for Kuberhealthy 2.0.0.

**Comment by jonnydawg** [comment]
Tabling this for now because we still need to decide on a good solution for handling certs.

Looks like others in the community like utilizing keygen scripts.

We could look at a cert manager?

**Comment by joshulyne** [comment]
@integrii I don't know if we still want to keep this issue around. I believe we created a workaround for this by using "unstructured" khchecks so that we can catch when checks aren't configured properly and it doesn't block the main kuberhealthy process. The only thing we have left is applying the same logic to khjobs which we have an issue for #602

**Comment by integrii** [comment]
Agreed!  I think our current support is good enough.  Also, setting up an admission controller is complex and requires SSL cert issuing, which can't easily be done in a simple `helm install`.
