### ISSUE TITLE
Gracefully detect when checker pods are shutdown or deleted expectedly and don't throw an error that the pod never reproted in 

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#223]
This issue is for Kuberhealthy 2 only.

When a check pod is running, the node under it may be cordoned and drained on purpose.  In this situation, we want to avoid indicating that the checker pod never reported in and instead should reschedule the checker pod.  Currently, any time a checker pod is evicted and does not check in, Kuberhealthy will eventually hit a timeout and think that the pod never checked in as expected.  

You can see this behavior by running the example test check and doing a `kubectl delete pod` on it as soon as it disappears.

It is not exactly clear to me how we want to identify when a pod has gone away "expectedly" vs timing out.  We should think carefully about how to identify this situation before adding it into the external checker logic.

**Comment by joshulyne** [comment]
This should include check pods that are deleted before it's `runInterval`. When new checks are added, deleted, modified -- kuberhealthy stops / deletes all running check pods to reconfigure all of them, but doesn't provision new pods for these checks until the check's next `runInterval`. Therefore, KH assumes the checker pod never reported in and reports the check as a failure.

**Comment by integrii** [comment]
addressed in c6b2df0db4c39a5f0beff9bbe5fce8f76c406ea8
