### ISSUE TITLE
Move away from static secrets in khcheck configs 

### ISSUE THREAD

**Issue by joshulyne** [Comcast/kuberhealthy#229]
**Describe the bug**
Right now we are providing static secrets in order to implement the khcheck daemonset check -- pr #207 

Investigate how helm or other config management tools manage config secrets

**Comment by integrii** [comment]
To reiterate the challenge here:

- When we distribute `khcheck` resources, they will often times need to come with RBAC configuration yamls
- These configuration YAMLs bind to a service account
- Providing a static service account is a security issue (it can be used to login to the cluster)
- Asking the user to run a second `kubectl create serviceaccount blah` command is not ideal.  We prefer them to be able to just run `kubectl apply -f` to enable more checks

Really, we would like some way to generate a unique service account without the user doing more than `kubectl apply -f`.

**Comment by joshulyne** [comment]
Possible proposal #230

**Comment by jonnydawg** [comment]
Kubernetes will handle your secrets for you if you apply a yaml just like:

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-khcheck
  namespace: kuberhealthy
```

**Comment by integrii** [comment]
Ah-hah!  So this is as simple as leaving the secret out of the specs entirely.  Closing this and #230 then!
