### ISSUE TITLE
Kuberhealthy to create ServiceAccounts for external checks

### ISSUE THREAD

**Issue by joshulyne** [Comcast/kuberhealthy#230]
**Describe the solution you would like to see happen**
To address issue #229 on having to deal with static secrets for khcheck configurations, we could create the service account in the check itself.

**How do you propose we build it?**
In the external khcheck, we add an initial functionality where it checks to see if a serviceaccount with the same name as the khcheck exists. If it doesn't, we proceed to create a serviceaccount with the same name as the khcheck and the necessary secret. Make sure the serviceaccount name is added to the config files: khcheck, role, and rolebinding. Add documentation on how to clean up the additional configs (role, rolebinding, service account, and secret) when someone wants to remove this khcheck.

**Comment by integrii** [comment]
I think using `kubectl delete -f` on the same yaml file used to apply the check makes for the easiest cleanup.  The kuberhealthy functionality could be as follows:

- When a new check is created, kuberhealthy checks if a service account using the same name exists (TODO: what if the user has specified a different service account in the pod yaml?)
- If the service account for the check name does not exist, kuberhealthy creates one along with a unique secret
- When the check is removed, kuberhealthy will check if the service account for the check exists
- if the serviceaccount does exist, and was created by kuberhealthy automatically, it is removed automatically

This means that:
- The `khcheck` yaml will specify everything (RBAC, `khcheck`, etc) EXCEPT the actual `serviceaccount` and secret that goes with it
- The user will not have to do more than `kubectl apply -f` or `kubectl delete -f` to add/remove `khcheck` resources in the cluster.

**Comment by joshulyne** [comment]
Would it be helpful to pass in a bool env var in the khcheck to specify whether or not the check requires a service account? Or do you think all external checks would require one?

**Comment by integrii** [comment]
Many checks won't make API calls and won't need a serviceaccount, but I would not like to have users blocked by a hidden bool var they need to flip on before they get access.  I would prefer we just prepare and use the service account for everything, even if they don't use it.

**Comment by integrii** [comment]
It turns out that just adding a serviceaccount into a cluster will automatically create the secret, even if you're using `kubectl apply -f`.  You never need to run `kubectl create secret` if you are deploying a khcheck.
