### ISSUE TITLE
externalCheckReportHandler should auto-deny any IP from outside the cluster

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#231]
Because the endpoint for `externalCheckReportHandler` does several API lookups over a duration to give fast running checker pods time to appear in the API pod list, we should consider the endpoint dangerous for any public consumption.

This means that any request going to the `externalCheckReportHandler` from sources outside the cluster should automatically be denied.  We should design this in a way that clusters with custom IP ranges don't need to do any extra configuration.

- find all internal IP ranges in the cluster
- if the calling source IP is not within one of the ranges in the cluster, then return an access denied status code

Relevant handler: https://github.com/Comcast/kuberhealthy/blob/2.0.0/cmd/kuberhealthy/kuberhealthy.go#L733

**Comment by zjhans** [comment]
After further discussion with Eric, making changes to this could potentially break Kuberhealthy for users. Closing this issue for now.
