### ISSUE TITLE
Create a Javascript module for reporting status to Kuberhealthy and an example check for it

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#237]
It would be nice to have a Javascript module and example `khcheck` for Javascript developers to start with when writing their own checks.

**Comment by integrii** [comment]
docs for making your own check client: https://github.com/Comcast/kuberhealthy/blob/2.0.0/docs/EXTERNAL_CHECK_CREATION.md

**Comment by jonnydawg** [comment]
new doc should be at:
https://github.com/Comcast/kuberhealthy/blob/master/docs/EXTERNAL_CHECK_CREATION.md

**Comment by jonnydawg** [comment]
Also looking at OAS for this for clients in multiple languages

**Comment by jonnydawg** [comment]
This has been created, but the client is intermittently posting status. 

![image](https://user-images.githubusercontent.com/12464614/78174203-be0ad800-740d-11ea-9e1f-c273933634bd.png)

**Comment by jonnydawg** [comment]
Going to take a look at async / Promises

**Comment by jonnydawg** [comment]
addressed by @gwolf3 in #476

**Comment by jonnydawg** [comment]
There is a sample javascript check under the `clients/` directory. Documentation about using a javascript client has been updated to include @gWOLF3 NPM package. [here](https://github.com/Comcast/kuberhealthy/blob/master/docs/EXTERNAL_CHECK_CREATION.md) and [here](https://github.com/Comcast/kuberhealthy/blob/master/clients/js/README.md)
