### ISSUE TITLE
Add configmap support with live-reloading to Kuberhealthy

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#252]
Instead of using a lot of different flags to configure Kuberhealthy, we could refactor to use a configmap yaml.

If we do this, I believe we should ensure that the configmaps are automatically reloaded when they change so that users don't have to bounce kuberhealthy pods when making changes.

**Comment by integrii** [comment]
@joshulyne has reminded me that we need to make sure [this readme](https://github.com/Comcast/kuberhealthy/blob/master/docs/FLAGS.md) is updated as part of this PR.

**Comment by jdowni000** [comment]
I have added configmap and monitoring features to automatically reload checks in the event the configmap has changed. I additionally have updated the readme and created a configuration readme as well

**Comment by joshulyne** [comment]
#557
