### ISSUE TITLE
deployment check in kh2 can leave deployment pods

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#254]
The deployment check in kh2 can leave deployment pods if terminated before completion.

We should be sure that the deployment check captures shutdown signals and appropriately cleans up pods before terminating.  We should also ensure that the khcheck yaml allows enough `terminationGracePeriodSeconds` time for the cleanup to complete.

![image](https://user-images.githubusercontent.com/98695/68440916-5368af80-0181-11ea-9479-ddf5dba5320b.png)

**Comment by jonnydawg** [comment]
Related to #261

**Comment by integrii** [comment]
Let's re-open if this is still an issue after #261 is found
