### ISSUE TITLE
Pod status checker false-positives

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#256]
**Describe the bug**
I see an alert in one of our test clusters that displays a lot of pods in the state of `Failed`, but looking at the pods manually with `kubectl` does not display anything with `Failed` at all.  It appears the client used by `pod-status` is fetching `Failed` pods that set off alarms, but those pods don't really exist.

**Screenshots**
![image](https://user-images.githubusercontent.com/98695/68634978-fd12ae00-04ab-11ea-9af2-7f682b6592c4.png)

![image](https://user-images.githubusercontent.com/98695/68635009-17e52280-04ac-11ea-877e-076eb3ecc174.png)

**Versions**
- 2.0.0rc1
- quay.io/comcast/pod-status-check:1.1.0

**Extra Info**

It appears something changed in the kubernetes client.  If you see the example below, `kubectl` 1.15 shows pods (but not their status for some reason, even when `-o wide` is used).  However, using `kubectl` 1.9, I can't see the pods at all.

![image](https://user-images.githubusercontent.com/98695/68635201-a5287700-04ac-11ea-855c-814b51bafb1c.png)

However, `kubectl` 1.9 WAS able to DELETE the pod it can't see: 
![image](https://user-images.githubusercontent.com/98695/68635228-b96c7400-04ac-11ea-8807-f6e7df16d21a.png)

Weird...

**Comment by rukatm** [comment]
`kubectl` 1.14.7
Checked status of pods and they are either `Evicted` or `OutOfcpu` with a `Status` of `Failed`.  

![image](https://user-images.githubusercontent.com/42722077/68635669-203e5d00-04ae-11ea-92c0-8c404c9d7173.png)

![image](https://user-images.githubusercontent.com/42722077/68635698-3815e100-04ae-11ea-888e-923673282664.png)

**Comment by integrii** [comment]
I am getting some of these tonight right when Kuberhealthy does a rolling update.  I think the root cause is different, but the result is the same: false positives from the pod status checker.

AVAB says it has pod-restarts in phase pending
![image](https://user-images.githubusercontent.com/98695/68672377-53143f80-0506-11ea-9ad0-1df09154e91d.png)

but if you look at the pod's description, it wasn't in pending for hardly any time at all:
![image](https://user-images.githubusercontent.com/98695/68672426-74752b80-0506-11ea-900f-d63d1a9eeca1.png)


I also had the exact same alert happen in AORB but it cleared before I could screenshot the issue here.  To reproduce, we could try rolling the kuberhealthy pods a few times in a cluster.

**Comment by integrii** [comment]
This seems to be working right now.  Moving to the 2.1.0 milestone for further investigation.  If you think this is fixed, we can close and re-open if we find otherwise.

**Comment by integrii** [comment]
We need #265 to help troubleshoot this, but I think it may be a non issue.
