### ISSUE TITLE
DNS external checker NPE

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#259]
I found an NPE in the DNS status checker:

![image](https://user-images.githubusercontent.com/98695/68658237-ec812880-04e9-11ea-83d7-4e57ab66fd78.png)

**Comment by joshulyne** [comment]
Built and pushed a new dns-status-check image with the latest KH checkclient package that addresses the NPE when reporting to KH. Changed the helm chart image pull policy for this dns-status-check-internal/external to `Always` to take in the latest changes when it's redeployed to our clusters
