### ISSUE TITLE
Publish a helm chart

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#26]
As of right now, the helm chart has no icon because we do not have an approved and trade-markable icon to use.  When we do, we should add one.  

Relevant to original issue #25

**Comment by integrii** [comment]
We now have a log from #22.  We should contribute the chart to helm so users can easily `helm install` it.  Update the recommended installation instructions once the PR is accepted.

https://github.com/helm/charts/blob/master/CONTRIBUTING.md

**Comment by integrii** [comment]
Looks like builds for helm are working again. There are a few issues to fix there with CircleCI:
https://circleci.com/gh/helm/charts/38980?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by integrii** [comment]
I am bumping the people assigned to review on slack via the #helm-users channel on the Kubernetes slack.  The charts look good to go and are only pending manual review...

**Comment by integrii** [comment]
I was able to get someone's ear today at Kubecon.  I started a new branch to remove an image that was committed by accident: https://github.com/helm/charts/pull/9955

**Comment by lolimjake** [comment]
Chart has passed all tests and is ready for someone from helm to merge it in https://github.com/helm/charts/pull/10158
