### ISSUE TITLE
Deployment check crashes

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#261]
I haven't been able to find the exact crash, but it is clear that the deployment checker sometimes crashes, leaving pods around.  Here are other checks that all indicate this is happening:

![image](https://user-images.githubusercontent.com/98695/68678818-87422d00-0513-11ea-9399-8d74d259db17.png)

the leftover pods from it: 
![image](https://user-images.githubusercontent.com/98695/68678805-827d7900-0513-11ea-861a-7891c29792dd.png)

**Comment by jonnydawg** [comment]
I've added some `== nil` checks throughout the deployment check code to hopefully prevent future crashes: https://github.com/Comcast/kuberhealthy/commit/f9f976c9a2866e695cdbfe6a48f1f87ae9aa3665

Hopefully this will help

**Comment by integrii** [comment]
These seem to be okay right now - moving to the 2.1.0 milestone.  KH2 leaves pods around longer, so we may be able to get a log on the crash.

**Comment by jonnydawg** [comment]
I've also added a catch incase panics occur -- these should be reported to KH2.

**Comment by integrii** [comment]
this is looking good in image 1.0.2 so far I think

**Comment by integrii** [comment]
I was able to capture a failure in the logs tonight!
![image](https://user-images.githubusercontent.com/98695/69037569-fe0c7980-099c-11ea-8aca-111712deffdd.png)

**Comment by integrii** [comment]
```
time="2019-11-18T08:40:52Z" level=error msg="Failed to create daemon set:DaemonSet.apps \"daemonset-test-kuberhealthy-56f6fd8745-fc726-daemonset-1574066447\" is invalid: [metadata.labels: Invalid value: \"daemonset-test-kuberhealthy-56f6fd8745-fc726-daemonset-1574066447\": must be no more than 63 characters, spec.selector.matchLabels: Invalid value: \"daemonset-test-kuberhealthy-56f6fd8745-fc726-daemonset-1574066447\": must be no more than 63 characters, spec.template.labels: Invalid value: \"daemonset-test-kuberhealthy-56f6fd8745-fc726-daemonset-1574066447\": must be no more than 63 characters]"
```

**Comment by integrii** [comment]
![image](https://user-images.githubusercontent.com/98695/69469452-db37e780-0d45-11ea-9f8c-35c3b40553be.png)

Looks like the daemonset is making pods with names that are too long.  Perhaps shorten the prefix of the ds test pods @joshulyne ?
