### ISSUE TITLE
pod-status sees its own pod in status Failed

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#267]
It looks like pod-status does not have the right client namespace set and is fetching failures from multiple namespaces.

**Steps To Reproduce**
- have two pod-status checks running in different namespaces
- have a pod fail in one of the two namespaces
- observe two failure alerts

**Expected behavior**
Only one pod should show a failure - the pod who is responsible for that namespaces

**Screenshots**

![image](https://user-images.githubusercontent.com/98695/68982663-c1822780-07bc-11ea-9a3c-221a9ddc5451.png)
[snip]
![image](https://user-images.githubusercontent.com/98695/68982773-2dfd2680-07bd-11ea-9b06-63b37bb1940e.png)

**Versions**
 - Kubernetes Version: 1.11
 - Kuberhealthy Release or build 2.0.0
 - pod status checker: 
```
      image: quay.io/comcast/pod-status-check:1.1.0
      imagePullPolicy: IfNotPresent
```

**Comment by integrii** [comment]
on second look here, it is expected that both pods have the same name.  This isn't necessarily two errors from the same namespace - this could be both pods erroring out for the same reason...

**Comment by integrii** [comment]
related to #256?

**Comment by rukatm** [comment]
Both pods erroring for the same reason could be it.  Attempted to repro with 3 failed pods across 2 namespaces and the output appears to be as expected where each responsible checker pod is reporting their corresponding failures.

![image](https://user-images.githubusercontent.com/42722077/68985591-7112c600-07cc-11ea-8de2-a2cd91491a36.png)
[snip]
![image](https://user-images.githubusercontent.com/42722077/68985617-9b648380-07cc-11ea-998c-647f3afe69c2.png)

**Comment by integrii** [comment]
Good data!  We will keep hunting the root cause, then.

**Comment by integrii** [comment]
Closing in favor of #256 - if there actually is an issue it hasn't been happening lately.
