### ISSUE TITLE
pod-restarts timed out while waiting for pod to exit

### ISSUE THREAD

**Issue by rukatm** [Comcast/kuberhealthy#274]
**Describe the bug**
Pod restarts timed out while waiting for pod to exit.

**Screenshots**
![image](https://user-images.githubusercontent.com/42722077/70003844-4db08080-1519-11ea-9cc6-715d6793778f.png)

**Additional context**
Happened to catch this while running a tail on the pod's log.  Previous occurrences were not caught as the checker pod's history was not available (being addressed in https://github.com/Comcast/kuberhealthy/issues/265).

**Comment by joshulyne** [comment]
Hmm so this should be an older version of the pod-restarts check. Since we just re-deployed to all the bravo clusters, we shouldn't see this error anymore ^

**Comment by jonnydawg** [comment]
Pod-restarts was unable to report to KH -- received a 500 internal:

![image](https://user-images.githubusercontent.com/12464614/70075514-d1b64700-15b1-11ea-9acd-20bee0545334.png)

**Comment by integrii** [comment]
We need #265 to help troubleshoot this.
