### ISSUE TITLE
Add a check that pods are reachable from all nodes

### ISSUE THREAD

**Issue by strigazi** [Comcast/kuberhealthy#278]
**Describe the solution you would like to see happen**
Similar to checking the pod status, it would be interesting to check that every k8s-node can reach a pod in a given namespace. The reasoning behind this it to catch CNI issues. For example, podA  in nodeX gets an IP from the CNI but podB in nodeY can not reach it (.i.e the CNI config is wrong).

**How do you propose we build it?**
A very simple approach would be a DS pinging all pods (in a namespace or anywhere else). Then the KuberhealthyCheck container would collect data advertised by all pods of the DS. This way we can be sure that future and current pods in any given node can reach the pods we want to monitor. 

**Additional context**
The example bug we faced was, after a reboot, in some nodes, flannel was not working properly and traffic could not reach pods in the problematic nodes.

I am thinking to implement this for our users anyway (not sure if it makes sense to do it as kuberhealthy check yet), but it would be great if other can have an option to use it.

I am opening this issue for your feedback.

Thanks!

**Comment by integrii** [comment]
This seems similar to #213 almost, but #213 didn't include networking.

It sounds like it could be possible to create a check that then spawns a daemonset to verify every node can ping a specific IP.  This would require the target IP to always be available, though.  Also, if routes were bad to just a hand full of nodes, the check may not catch the issue.  

It sounds like we might need here is a full mesh of checks to verify that every chunk of IPs allocated by the CNI can communicate with every other node in the cluster...?

**Comment by strigazi** [comment]
I am giving this a go:
https://github.com/postfinance/kubenurse
