### ISSUE TITLE
Flat specs do not include CRD information

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#279]
**Describe the bug**
Our flat spec files do not include the namespace or CRD definitions.

**Steps To Reproduce**
- Confirm that custom resource definitions are available in the `crds` directory in the helm chart
- Use helm 3 to run `helm template` on our chart
- Notice specs are not present

**Expected behavior**
CRD definitions should be in the output YAML

**Additional context**
It looks like Helm is addressing the issue here: https://github.com/helm/helm/issues/6930 and we're waiting for a release.  Until then, we should update our `deploy/helm/create-flat-files.sh` script so that it prepends our CRDs to the flat files it generates.

**Comment by integrii** [comment]
This is "fixed" by using the new bash scripts for generating a static manifest, but I am leaving this issue open so we remember to clean these bash fixes up after Helm makes their fix and starts outputting CRDs in `helm template`.

**Comment by mtougeron** [comment]
I'm attempting to solve this via https://github.com/helm/helm/pull/7440 (1st contrib so we'll see...)

**Comment by integrii** [comment]
Good luck @mtougeron !

**Comment by integrii** [comment]
closing this. we will open a new issue if this impacts use
