### ISSUE TITLE
It is unfriendly for new users

### ISSUE THREAD

**Issue by fengzixu** [Comcast/kuberhealthy#286]
**Describe the bug**

First of all,  if I want to use this link (kubectl apply -f https://raw.githubusercontent.com/Comcast/kuberhealthy/deploy/kuberhealthy.yaml) to deploy the kuberhealthy, I got the 404 error. Because there is no master path in the url.
> kubectl apply -f https://raw.githubusercontent.com/Comcast/kuberhealthy/deploy/kuberhealthy.yaml
error: unable to read URL "https://raw.githubusercontent.com/Comcast/kuberhealthy/deploy/kuberhealthy.yaml", server reported 404 Not Found, status code=404
> 

Second, the description of installation is not clear:https://github.com/Comcast/kuberhealthy#installation. According to this doc, I think you recommend users need to use orchestration file in `deploy` dir to deploy the kuberhealthy. But there is no crd definition in https://github.com/Comcast/kuberhealthy/blob/master/deploy/kuberhealthy.yaml.  I need to find the CRD definition on deploy/helm dir.

So, Can you revise the README? I think there are some potential problems

**Comment by jonnydawg** [comment]
Thanks for bringing this up!

Seems like there is an issue with Helm templating CRDs.

**Comment by integrii** [comment]
With the PR I just opened and the fixes in the 2.1 branch for CRDs (as described in #279), both of these issues should be fixed.

Thank you for taking the time to make an issue for this.  We really appreciate the feedback.
