### ISSUE TITLE
Publish Kuberhealthy as a Helm Repository

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#288]
The process of updating our Helm chart is slow and cumbersome.  It often takes us longer to update the chart than it does to add a new feature and modify our templates.  This means our Helm installation is almost always out of date.

As suggested by @davidkarlsen [here](https://github.com/helm/charts/pull/18899#issuecomment-571386038), we should revisit having our own repository added as a Helm repository.  This would give us the ability to self-publish Helm charts.

This means following [the documentation here](https://github.com/helm/hub/blob/master/Repositories.md) to submit a PR to helm/hub.

**Comment by davidkarlsen** [comment]
Do you have a repo already? We have some github actions to facilitate testing and releasing charts using github-pages as chart repo.

**Comment by integrii** [comment]
We haven't yet done this one... We have not filed a PR with `helm/hub` to have our repo listed as a repository yet.

The current helm chart we are developing against is [here](https://github.com/Comcast/kuberhealthy/tree/2.1/deploy/helm).

**Comment by integrii** [comment]
removing this from readme

```

> [Helm 3](https://helm.sh/) required for all chart installation.
> 
> To install using Helm 3 *without* Prometheus metrics:
> `helm install stable/kuberhealthy`
> 
> To install using Helm 3 *with* Prometheus metrics:
> `helm install stable/kuberhealthy --set prometheus.enabled=true --set prometheus.enableScraping=true --set prometheus.enableAlerting=true`
> 
> To install using Helm 3 *with* a Prometheus `ServiceMonitor`:
> `helm install stable/kuberhealthy --set prometheus.enabled=true --set prometheus.enableScraping=true --set prometheus.enableAlerting=true --set prometheus.serviceMonitor=true`
 
You can also use a flat spec file if you don't want to use Helm:
```

**Comment by chadbitzer** [comment]
Working on this, index.yaml and .tgz file have been added and submitted in PR for master.  Next will be push master to gh-pages branch, then add relevant data to Helm Project's config/repo-values.yaml & repos.yaml, and submit PR to have those additions merged.

**Comment by integrii** [comment]
In response to the PR open for this in #379 ... I think we need to refactor in the following way:

- Create a new `helm-repos` directory at the project root
- Create a new `helm-repos/kuberhealthy` directory and place a tar file in it as gerated from `helm package`
- Create a new `helm-repos/index.yml` file using the [example here](https://github.com/microsoft/charts/blob/master/repo/index.yaml).
- Merge PR #379 into master
- Create and merge a PR into our `gh-pages` branch from the newly updated master
- Open a PR against the helm project to add a new entry for us to [this file](https://github.com/helm/hub/blob/master/config/repo-values.yaml).

**Comment by chadbitzer** [comment]
PR #379 ready for review to merge into master

**Comment by chadbitzer** [comment]
Versioning has been corrected to 2.1.0 in PR #379, ready for review.

**Comment by integrii** [comment]
This is blocked because Helm throws an error that the namespace does not exist, even though a `namespace` template exists in the chart.  Helm has merged a PR to add a new `--create-namespace` flag that will fix this, but stable released versions do not yet have the functionality.

We need to figure out how to make `helm install` properly create a namespace and apply the chart without errors...

**Comment by integrii** [comment]
This is done!  @chadbitzer figured out that we needed to remove our `namespace` spec to be compatible with Helm 3.
