### ISSUE TITLE
DaemonSetChecker references deprecated API endpoints

### ISSUE THREAD

**Issue by stenwt** [Comcast/kuberhealthy#291]
**Describe the bug**
As of k8s 1.16, the extensions/v1beta1 endpoint is deprecated and removed for daemonsets (among others): https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ . Since the Kuberhealthy daemonset checker uses that endpoing, daemonsets can't be deployed on K8s 1.16+. 

**Steps To Reproduce**
Deploy kuberhealthy to k8s 1.16+
Daemonset checker fails with a message ending, "the server could not find the requested resource"

**Expected behavior**
The daemonset checker should run successfully

**Versions**
 - Kubernetes Version: 1..16+

**Additional context**
Proposed fix: https://github.com/Comcast/kuberhealthy/pull/290

**Comment by integrii** [comment]
Thanks @stenwt!  I really appreciate you following up with the PR to fix this.

I will test your PR today.  My only concern is backwards compatibility.  Currently, Kuberhealthy accepts back to as far as 1.9 (but obviously not to 1.16) so I want to be careful before I orphan existing users with a new release.
