### ISSUE TITLE
While deploying kuberhealthy yaml file, I encountered an issue saying unable to recognize "kuberhealthy.yaml": no matches for kind "KuberhealthyCheck" in version "comcast.github.io/v1".

### ISSUE THREAD

**Issue by amarAkula** [Comcast/kuberhealthy#292]
Description-
poddisruptionbudget.policy/kuberhealthy-pdb created
serviceaccount/daemonset-khcheck created
serviceaccount/deployment-sa created
serviceaccount/kuberhealthy created
clusterrole.rbac.authorization.k8s.io/kuberhealthy created
clusterrolebinding.rbac.authorization.k8s.io/kuberhealthy created
role.rbac.authorization.k8s.io/ds-admin created
role.rbac.authorization.k8s.io/deployment-service-role created
rolebinding.rbac.authorization.k8s.io/daemonset-khcheck created
rolebinding.rbac.authorization.k8s.io/deployment-check-rb created
service/kuberhealthy created
deployment.apps/kuberhealthy created
unable to recognize "kuberhealthy.yaml": no matches for kind "KuberhealthyCheck" in version "comcast.github.io/v1"
unable to recognize "kuberhealthy.yaml": no matches for kind "KuberhealthyCheck" in version "comcast.github.io/v1"
unable to recognize "kuberhealthy.yaml": no matches for kind "KuberhealthyCheck" in version "comcast.github.io/v1"

**Versions**
 - CentOS Linux release 7.7.1908 (Core)
 - Kubernetes Version: 1.15.4

Is helm necessary for kuberhealthy?

**Comment by gWOLF3** [comment]
same here - related to this?

```
Helm installations are currently not available from helm/charts/kuberhealthy due to a slow PR process. For now, use the flat files below.
```

**Comment by amarAkula** [comment]
Thanks, I have deployed the crds.
After deploying the yaml files in deploy folder iam seeing this.
poddisruptionbudget.policy/kuberhealthy-pdb created
configmap/kuberhealthy created
serviceaccount/daemonset-khcheck created
serviceaccount/deployment-sa created
serviceaccount/kuberhealthy created
clusterrole.rbac.authorization.k8s.io/kuberhealthy created
clusterrolebinding.rbac.authorization.k8s.io/kuberhealthy created
role.rbac.authorization.k8s.io/ds-admin created
role.rbac.authorization.k8s.io/deployment-service-role created
rolebinding.rbac.authorization.k8s.io/daemonset-khcheck created
rolebinding.rbac.authorization.k8s.io/deployment-check-rb created
service/kuberhealthy configured
deployment.apps/kuberhealthy created
kuberhealthycheck.comcast.github.io/daemonset created
kuberhealthycheck.comcast.github.io/deployment created
kuberhealthycheck.comcast.github.io/dns-status-internal created
poddisruptionbudget.policy/kuberhealthy-pdb created
configmap/kuberhealthy created
serviceaccount/daemonset-khcheck created
serviceaccount/deployment-sa created
serviceaccount/kuberhealthy created
clusterrole.rbac.authorization.k8s.io/kuberhealthy created
clusterrolebinding.rbac.authorization.k8s.io/kuberhealthy created
role.rbac.authorization.k8s.io/ds-admin created
role.rbac.authorization.k8s.io/deployment-service-role created
rolebinding.rbac.authorization.k8s.io/daemonset-khcheck created
rolebinding.rbac.authorization.k8s.io/deployment-check-rb created
service/kuberhealthy created
deployment.apps/kuberhealthy created
kuberhealthycheck.comcast.github.io/daemonset created
kuberhealthycheck.comcast.github.io/deployment created
kuberhealthycheck.comcast.github.io/dns-status-internal created
poddisruptionbudget.policy/kuberhealthy-pdb created
serviceaccount/daemonset-khcheck created
serviceaccount/deployment-sa created
serviceaccount/kuberhealthy created
clusterrole.rbac.authorization.k8s.io/kuberhealthy created
clusterrolebinding.rbac.authorization.k8s.io/kuberhealthy created
role.rbac.authorization.k8s.io/ds-admin created
role.rbac.authorization.k8s.io/deployment-service-role created
rolebinding.rbac.authorization.k8s.io/daemonset-khcheck created
rolebinding.rbac.authorization.k8s.io/deployment-check-rb created
service/kuberhealthy configured
deployment.apps/kuberhealthy created
kuberhealthycheck.comcast.github.io/daemonset created
kuberhealthycheck.comcast.github.io/deployment created
kuberhealthycheck.comcast.github.io/dns-status-internal created
**unable to recognize "deploy/kuberhealthy-prometheus-operator.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "deploy/servicemonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"**

**Comment by integrii** [comment]
There are a couple things going on here.  First, the metadata for `namespace` is not coming along in all objects, causing permissions issues from incorrect service accounts and roles and such.  Secondly, there was issue #279 which resulted in a bug from Helm wherein CRDs were not output when using `helm template`.

In response to some talk on Slack today, I have been modifying (along with @rukatm) the kuberhealthy chart to ensure that the `namespace:` is explicitly set in all places in the spec.  

As things progress, we are currently putting patches in the 2.1 branch.  [This is the current "best" version of the spec.](https://github.com/Comcast/kuberhealthy/blob/2.1/deploy/kuberhealthy.yaml)  We are actively working on this and it should be fixed tomorrow.  Try that spec and if it's not working after tomorrow, leave another update here if you could.

**Comment by integrii** [comment]
I think this issue has been resolved after conversation in Slack over the past couple weeks.  Please let me know if that is not the case.
