### ISSUE TITLE
Set khcheck environment variables in Helm chart 

### ISSUE THREAD

**Issue by zeleena** [Comcast/kuberhealthy#322]
**Set khcheck environment variables in the Helm chart**
As per the READMEs (i.e. https://github.com/Comcast/kuberhealthy/tree/master/cmd/deployment-check), there are many configurable environment variables for the khchecks. However, with the current helm chart in this repo, there is no way to set these environment variables in the values file nor from the helm chart template (https://github.com/Comcast/kuberhealthy/blob/master/deploy/helm/kuberhealthy/templates/khcheck-deployment.yaml#L16-L20).

Can we add functionality to be able to set the configurable environment variables for khchecks in the helm chart? Similar to [this change](https://github.com/Comcast/kuberhealthy/pull/321); I made a feature request rather than a PR, figuring this addition might want to be standardized in some way.

**Specific use case**
Specifically, I wanted to be able to set `CHECK_IMAGE` and `CHECK_IMAGE_ROLL_TO` in the deployment khcheck and `PAUSE_CONTAINER_IMAGE` in the daemonset khcheck (see https://github.com/Comcast/kuberhealthy/blob/master/cmd/daemonSetCheck/main.go#L84) to be able to set them to custom images, since the defaults don't work for our use case.

**Comment by integrii** [comment]
You fixed your own issue!  Badass.
