### ISSUE TITLE
Pod Status Check has insufficient permissions

### ISSUE THREAD

**Issue by zeleena** [Comcast/kuberhealthy#325]
**Describe the bug**
After deploying the helm chart from this repo and enabling the pod status check in the values file, the pod status check returns error:
`"pods is forbidden: User \"system:serviceaccount:kuberhealthy:default\" cannot list resource \"pods\" in API group \"\" in the namespace \"kuberhealthy\""`

**Steps To Reproduce**
- Deploy the helm chart from this repo into the kuberhealthy namespace, and modify the values file for podStatus to enabled: true
- Apply typo fix from https://github.com/Comcast/kuberhealthy/pull/318
- View the output on the status page, OK will be false with the above error

**Expected behavior**
OK would be true, or give an error related to the pod statuses and not permissions

**Screenshots**
Error message from report page:
![image](https://user-images.githubusercontent.com/12972510/75268893-170b9e80-57c6-11ea-8eef-e4343faa21af.png)

**Versions**
 - Cluster OS: Ubuntu 18.04
 - Kuberhealthy Release or build v2.1.2
- Pod Status Check v1.1.0 (and tried with more recent v1.0.2 too)

**Additional context**
Like mentioned above, there are Pod Status Check image versions 1.1.0 and 1.0.2 (which is more recent), but I attempted with both and got the same result.

**Comment by integrii** [comment]
This probably needs another test using the helm chart in `deploy/helm` because several things have changed in the chart since this issue was reported...

**Comment by integrii** [comment]
Hey @zeleena - we just rolled out a new chart for installation with Helm 3.  Check [this out](https://github.com/Comcast/kuberhealthy#installation) from our updated readme.

Could you give a fresh install a try?  This may fix your issue because the current chart is tested working.  Please re-open the issue if you find this not true.  Thank you!
