### ISSUE TITLE
Implement Clair into all github action builds 

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#347]
We should run the following tool on all of our Dockerfiles and fix any issues it reports:

https://github.com/docker/docker-bench-security

**Comment by integrii** [comment]
Looks like this is hard to implement due to the extremely specific on-disk libraries and things required.  It would be much easier to use a tool like [Docker enterprise](https://docs.docker.com/ee/dtr/user/manage-images/scan-images-for-vulnerabilities/) to automatically scan for vulnerabilities.

**Comment by integrii** [comment]
Looks like we should switch to [Clair](https://github.com/quay/clair/blob/master/Documentation/running-clair.md)...  The task here would be to run a Clair scan on every image produced from our Github Actions builds.

**Comment by jdowni000** [comment]
I was able to use third party package call instead of integrating Clair. This has been integrated already into Master branch
