### ISSUE TITLE
Rename all checks to lowercase names with dashes

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#354]
We need to rename our checks to be compatible with docker image names. This involves renaming the directory in `/cmd`, the image name being produced (in the `Makefile`) and finally the related github action.  We should also be sure to adjust the `README.md` for each check as well as the information in the `CHECKS_REGISTRY.md` file in `docs/`

- [x] `daemonSetCheck` -> `daemonset-check`
- [x] `dnsStatusCheck` -> `dns-resolution-check`
- [x] `podRestartsCheck` -> `pod-restarts-check`
- [x] `podStatusCheck` -> `pod-status-check`

Things to change on each:

- [ ] `docs/CHECKS_REGISTRY.md`
- [x] check `README.md`
- [x] check `cmd/` directory name
- [x] check's Makefile (ensure image name matches directory name of check)
- [ ] helm chart `khcheck` image URL

Documentation update:
- [ ] Update [external checks doc](https://github.com/Comcast/kuberhealthy/blob/master/docs/EXTERNAL_CHECKS.md) with proper check naming convention.

**Comment by joshulyne** [comment]
can we make sure to add in our [external checks doc](https://github.com/Comcast/kuberhealthy/blob/master/docs/EXTERNAL_CHECKS.md)
that we have this standard naming convention if people are interested in contributing checks?

**Comment by integrii** [comment]
added to main description as a checkbox
