### ISSUE TITLE
service account missing in deployment-check

### ISSUE THREAD

**Issue by NissesSenap** [Comcast/kuberhealthy#361]
**Describe the feature you would like and why you want it**
I need the possibility to add a service account to the deployment that that deployment-check creates through the khchecks.comcast.github.io deployment or something similar.

**Additional context**
I'm using openshift and due to the extra security context i need to be able to set a service account that got the possibility to create containers that runs as root user. The pod is currently started with the default serviceaccount and if i patch it, it get's replaced by the operator.

**Comment by jonnydawg** [comment]
Thanks for the work! Your PR was merged :)
