### ISSUE TITLE
ownerReferences added to all object

### ISSUE THREAD

**Issue by NissesSenap** [Comcast/kuberhealthy#366]
**Describe the feature you would like and why you want it**
Would love to see ownerReferences in all objects that is created by the kuberhealthy crd:s to make it easier to track what creates what and where to debug for new users.

**Additional context**
This is standard within k8s itself, for example see the check-reaper pod, you will see a ownerReference to the job object.

I think this will take some time, so but i don't think it's hard.

**Comment by joshulyne** [comment]
Hmm I believe in the checker pods, we have `kuberhealthy_check_name=pod-status` which is referencing the khcheck crd `pod-status` -- is this what you're referencing?

**Comment by integrii** [comment]
I think @NissesSenap means he wants us to implement [owner reference metadata](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#ownerreference-v1-meta).  I think this is a good idea to do!  Perhaps good for a first time contributor?
