### ISSUE TITLE
Kuberhealthy daemonset pods fail to get cleared up

### ISSUE THREAD

**Issue by cagiti** [Comcast/kuberhealthy#367]
**Describe the bug**
We've noticed that kuberhealthy pods are failing to be cleared up after their use. The logs show:
```bash
time="2020-03-11T03:02:40Z" level=error msg="Get https://<IP>443/api/v1/namespaces/jx/pods?fieldSelector=status.phase%3DRunning&labelSelector=app%3Dkuberhealthy: dial tcp <IP>:443: connect: connection refused"
time="2020-03-11T03:03:20Z" level=error msg="Get https://<IP>:443/api/v1/namespaces/jx/pods?fieldSelector=status.phase%3DRunning&labelSelector=app%3Dkuberhealthy: dial tcp <IP>:443: i/o timeout"
```

**Steps To Reproduce**
- Long running kuberhealthy instance it seems (some of ours have been running more that 30d

**Expected behavior**
Pods created by kuberhealthy are removed once they have completed their task

**Versions**
 - Kubernetes Version: v1.15.8-gke.3, v1.13.12-gke.25 (_happening on multiple cluster versions_)
 - Kuberhealthy Chart version: 1.2.6

**Additional context**
When deleting the kuberhealthy app pods then it seems to resolve the issue and the daemonset pods are cleared up as expected.

daemonset pods output
```bash
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1579889629-4fpfw     1/1     Running     0          52d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1579889629-nqmks     1/1     Running     0          52d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1579889629-vnzxt     1/1     Running     0          52d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1581142553-5dxqh     1/1     Running     0          37d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1581142553-99bls     1/1     Running     0          37d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1581142553-btpxn     1/1     Running     0          37d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1581451506-2b4zn     1/1     Running     0          34d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1581451506-4kqq4     1/1     Running     0          34d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1581451506-q9bbn     1/1     Running     0          34d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1582613991-gkb2g     1/1     Running     0          20d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1582613991-td84c     1/1     Running     0          20d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1582613991-xkvrr     1/1     Running     0          20d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1583102472-8xhm8     1/1     Running     0          15d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1583102472-9r6rw     1/1     Running     0          15d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1583102472-mnzs4     1/1     Running     0          15d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1583112675-9jr4s     1/1     Running     0          14d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1583112675-l75vf     1/1     Running     0          14d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1583112675-vndx4     1/1     Running     0          14d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1583257883-bbk2g     1/1     Running     0          13d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1583257883-l8jcr     1/1     Running     0          13d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1583257883-qgc6b     1/1     Running     0          13d
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1584159662-bwcdf     1/1     Running     0          3d5h
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1584159662-lh2pp     1/1     Running     0          3d5h
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1584159662-vcg7m     1/1     Running     0          3d5h
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1584344296-v7cmp     1/1     Running     0          18h
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1584344296-vxhjp     1/1     Running     0          18h
daemonset-test-kuberhealthy-849f8ccd74-4vtck-1584344296-zh54n     1/1     Running     0          18h
```

**Comment by joshulyne** [comment]
Hmm, seems like you are using an older version of Kuberhealthy. We've recently made a lot of changes with out 2.0.0 release -- making Kuberhealthy an operator for synthetic monitoring, giving devs the ability to add more synthetic checks easily -- and we also made more changes with our latest 2.1 release as well (this actually keeps checker pods around a bit longer so folks have more time to diagnose issues/failures, along with a check reaper that does the cleanup of older checker pods).

**Comment by integrii** [comment]
@cagiti could you try installing one of the flat file specs [here](https://github.com/Comcast/kuberhealthy/tree/master/deploy) to update to Kuberhealthy 2.1?  You can also use the helm chart provided there if you prefer.

**Comment by cagiti** [comment]
> @cagiti could you try installing one of the flat file specs [here](https://github.com/Comcast/kuberhealthy/tree/master/deploy) to update to Kuberhealthy 2.1? You can also use the helm chart provided there if you prefer.

I’ll try upgrading using the chart, thanks for getting back to me 👍

**Comment by cagiti** [comment]
Where can I find the latest chart version please? I'm using the latest hosted here https://hub.helm.sh/charts/stable/kuberhealthy/1.2.6

**Comment by integrii** [comment]
We're just about to finish #288 and you'll be able to use helm 3 to install the chart soon....

If you want to deploy before that, the most current specs would be here: https://github.com/Comcast/kuberhealthy/tree/master/deploy

You should probably use [this file](https://github.com/Comcast/kuberhealthy/blob/master/deploy/kuberhealthy.yaml) if you have a standard Kubernetes deployment.

**Comment by joshulyne** [comment]
@cagiti wondering if this is still an issue for you? hoping to close this out if possible!

**Comment by cagiti** [comment]
> @cagiti wondering if this is still an issue for you? hoping to close this out if possible!

We've not migrated over to Helm3 at the moment, so we'll need to look at moving to using the specs from https://github.com/Comcast/kuberhealthy/tree/master/deploy .

**Comment by joshulyne** [comment]
> > @cagiti wondering if this is still an issue for you? hoping to close this out if possible!
> 
> We've not migrated over to Helm3 at the moment, so we'll need to look at moving to using the specs from https://github.com/Comcast/kuberhealthy/tree/master/deploy .

**Comment by joshulyne** [comment]
@cagiti closing this issue for now -- feel free to open another issue if you're still running into problems!
