### ISSUE TITLE
Refactor test-external-check docs

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#372]
https://github.com/Comcast/kuberhealthy/tree/master/cmd/test-external-check

The docs for test-external-check talk about applying the KH 2.0.0 CRD.  This is a given these days but will still confuse people.  We should refactor the test docs to make more sense.

**Comment by 2infinitee** [comment]
added notes to the doc

https://github.com/Comcast/kuberhealthy/blob/ext-check-doc/cmd/test-external-check/README.md

**Comment by 2infinitee** [comment]
doc has been merged
