### ISSUE TITLE
Move all Docker images away from the root user

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#402]
All of our checker containers are running as root.  This breaks users as described in #400.  This also should be identified by the Dockerfile scanner we are adding in $401.

This issue is to track the progress of moving all images to use non-root user IDs.

**Comment by jdowni000** [comment]
i have updated each check to run the binary from a new user named user. PR has been submitted

**Comment by integrii** [comment]
Fixed in #406
