### ISSUE TITLE
testing issue pkg/external

### ISSUE THREAD

**Issue by NissesSenap** [Comcast/kuberhealthy#411]
Hi

After my updates to kuberhealthy/pkg/checks/external/main.go I thought i would see if i could write a test for my addition.

So I did a good old go test ./...
And hit some issues.

basicCheckerPod.yaml is currently pointing to image: integrii/kh-test-check, we should repoint this to "kuberhealthy/test-external-check:v1.2.0" or latest.

When I run the test it starts pod: kh-test-check-1586797890 and I find the following error:
Failed to parse REPORT_FAILURE env var: strconv.ParseBool: parsing "":

I added the following to basicCheckerPod.yaml:
          - name: "REPORT_FAILURE"
            value: "false"
          - name: "REPORT_DELAY"
            value: "10s"

Running the pod I get the following error:
2020/04/13 17:33:42 checkClient: DEBUG: Reporting SUCCESS
2020/04/13 17:33:42 checkClient: DEBUG: Sending report with error length of:0
2020/04/13 17:33:42 checkClient: DEBUG: Sending report with ok state of:true
2020/04/13 17:33:42 checkClient: INFO: Using kuberhealthy reporting URL:http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus
2020/04/13 17:33:42 checkClient: ERROR: got a bad status code from kuberhealthy:400400 Bad Request
2020/04/13 17:33:42 Error reporting to Kuberhealthy servers: bad status code from kuberhealthy status reporting url: %!s(int=400)%!(EXTRA string=400 Bad Request)

After this I realised there is a need for a bigger rewrite of the tests and created this issue.
I'm happy to send in the small fixes I have done as a PR but it's not much but I currently don't have all the knowledge to fix it myself.

I personally see this as two issues:
1. Fix the current tests.
2. Since all the parts is rather integrated with each other but we only perform tests when we build the container images ideally we would trigger a go test ./... for each PR. This way we will hopefully see if we hit a big issue.

Sadly this will be a pain since we need a k8s cluster and I assume you don't want to pay for it ^^.
Github action vm:s is rather big https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
2-core CPU
7 GB of RAM memory
14 GB of SSD disk space

So we could setup a kind/k3s/minikube "cluster" add kuberhealthy and run the tests.
It will ofc take a long time to download, setup + run the test but I think it's doable.

**Comment by NissesSenap** [comment]
So you don't have to wait for 10 min, this is the output from go test ./... from kuberhealthy/pkg/checks/external

2020/04/13 19:33:24 Loading config from flags...
time="2020-04-13T19:33:24+02:00" level=debug msg="Decoding this YAML: apiVersion: \"comcast.github.io/v1\"\nkind: \"KuberhealthyCheck\"\nmetadata:\n  name: \"kh-test-check\"\n  namespace: \"kuberhealthy\"\n  labels:\n    app: kuberhealthy\n  annotations: {}\nspec:\n  runInterval: 1m5s\n  uuid: \"TESTUUIDHERE\"\n  podSpec:\n    containers:\n      - env:\n          - name: \"SOME_ENV_VAR\"\n            value: \"12345\"\n          - name: \"REPORT_FAILURE\"\n            value: \"false\"\n          - name: \"REPORT_DELAY\"\n            value: \"10s\"\n        image: kuberhealthy/test-external-check:v1.2.0\n        imagePullPolicy: IfNotPresent\n        name: main\n        resources:\n          requests:\n            cpu: 10m\n            memory: 50Mi\n"
time="2020-04-13T19:33:24+02:00" level=debug msg="Creating external check from check config: {\n\t\"kind\": \"KuberhealthyCheck\",\n\t\"apiVersion\": \"comcast.github.io/v1\",\n\t\"metadata\": {\n\t\t\"name\": \"kh-test-check\",\n\t\t\"namespace\": \"kuberhealthy\",\n\t\t\"creationTimestamp\": null,\n\t\t\"labels\": {\n\t\t\t\"app\": \"kuberhealthy\"\n\t\t}\n\t},\n\t\"spec\": {\n\t\t\"runInterval\": \"1m5s\",\n\t\t\"timeout\": \"\",\n\t\t\"podSpec\": {\n\t\t\t\"containers\": [\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"main\",\n\t\t\t\t\t\"image\": \"kuberhealthy/test-external-check:v1.2.0\",\n\t\t\t\t\t\"env\": [\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\"name\": \"SOME_ENV_VAR\",\n\t\t\t\t\t\t\t\"value\": \"12345\"\n\t\t\t\t\t\t},\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\"name\": \"REPORT_FAILURE\",\n\t\t\t\t\t\t\t\"value\": \"false\"\n\t\t\t\t\t\t},\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\"name\": \"REPORT_DELAY\",\n\t\t\t\t\t\t\t\"value\": \"10s\"\n\t\t\t\t\t\t}\n\t\t\t\t\t],\n\t\t\t\t\t\"resources\": {\n\t\t\t\t\t\t\"requests\": {\n\t\t\t\t\t\t\t\"cpu\": \"10m\",\n\t\t\t\t\t\t\t\"memory\": \"50Mi\"\n\t\t\t\t\t\t}\n\t\t\t\t\t},\n\t\t\t\t\t\"imagePullPolicy\": \"IfNotPresent\"\n\t\t\t\t}\n\t\t\t]\n\t\t},\n\t\t\"extraAnnotations\": null,\n\t\t\"extraLabels\": null\n\t}\n} \n"
time="2020-04-13T19:33:24+02:00" level=info msg=" kuberhealthy/kh-test-check: [Validating pod spec of external check]"
time="2020-04-13T19:33:24+02:00" level=info msg=" kuberhealthy/kh-test-check: [Timeout set to 15m0s]"
time="2020-04-13T19:33:24+02:00" level=info msg=" kuberhealthy/kh-test-check: [Configuring spec of external check]"
time="2020-04-13T19:33:24+02:00" level=info msg=" kuberhealthy/kh-test-check: [Running sanity check on check parameters]"
time="2020-04-13T19:33:24+02:00" level=info msg=" kuberhealthy/kh-test-check: [Waiting for all existing pods to clean up]"
time="2020-04-13T19:33:24+02:00" level=info msg=" kuberhealthy/kh-test-check: [waiting for pod to clear]"
time="2020-04-13T19:33:24+02:00" level=debug msg="Waiting for checker pod kh-test-check-1586799204 to clear..."
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [all pods cleared]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [No checker pods exist.]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [creating pod for external check: kh-test-check]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [checker pod annotations and labels: map[] map[]]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [Creating external checker pod named kh-test-check-1586799204]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [creating a pod watcher]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [created a pod watcher successfully]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [starting pod shutdown watcher]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [got a result when watching for pod to remove]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [pod removal monitor saw an irrelevant event type and ignored it: ADDED]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [got a result when watching for pod to remove]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [pod removal monitor saw an irrelevant event type and ignored it: ADDED]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [got a result when watching for pod to remove]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [pod removal monitor saw an irrelevant event type and ignored it: ADDED]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [Unable to find kuberhealthy pod pods \"enorling.remote.csb\" not found]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [got a result when watching for pod to remove]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [pod removal monitor saw an irrelevant event type and ignored it: ADDED]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [got a result when watching for pod to remove]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [pod removal monitor saw an irrelevant event type and ignored it: ADDED]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [got a result when watching for pod to remove]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [pod removal monitor saw an irrelevant event type and ignored it: ADDED]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [Check kh-test-check created pod kh-test-check-1586799204 in namespace kuberhealthy]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [waiting for pod to be running]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [starting pod running watcher]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [got a result when watching for pod to remove]"
time="2020-04-13T19:33:29+02:00" level=info msg=" kuberhealthy/kh-test-check: [pod removal monitor saw an irrelevant event type and ignored it: ADDED]"
time="2020-04-13T19:33:30+02:00" level=info msg=" kuberhealthy/kh-test-check: [got a result when watching for pod to remove]"
time="2020-04-13T19:33:30+02:00" level=info msg=" kuberhealthy/kh-test-check: [checker pod shutdown monitor saw a modified event.]"
time="2020-04-13T19:33:30+02:00" level=info msg=" kuberhealthy/kh-test-check: [checker pod shutdown monitor saw a modified event. the pod changed to  Pending]"
time="2020-04-13T19:33:30+02:00" level=info msg=" kuberhealthy/kh-test-check: [got an event while waiting for pod to start running]"
time="2020-04-13T19:33:30+02:00" level=info msg=" kuberhealthy/kh-test-check: [pod state is now: Succeeded]"
time="2020-04-13T19:33:30+02:00" level=info msg=" kuberhealthy/kh-test-check: [pod is now either running, failed, or succeeded]"
time="2020-04-13T19:33:30+02:00" level=info msg=" kuberhealthy/kh-test-check: [External check pod is running: kh-test-check-1586799204]"
time="2020-04-13T19:33:30+02:00" level=info msg=" kuberhealthy/kh-test-check: [Waiting for pod status to be reported from pod kh-test-check-1586799204 in namespace kuberhealthy]"
time="2020-04-13T19:33:30+02:00" level=info msg=" kuberhealthy/kh-test-check: [waiting for pod to report in to status page...]"
time="2020-04-13T19:33:35+02:00" level=info msg=" kuberhealthy/kh-test-check: [waiting for external checker pod to report in...]"
.
.
.
time="2020-04-13T19:43:24+02:00" level=info msg=" kuberhealthy/kh-test-check: [have not yet seen pod update since 0001-01-01 00:00:00 +0000 UTC]"
panic: test timed out after 10m0s

goroutine 175 [running]:
testing.(*M).startAlarm.func1()
        /usr/local/go/src/testing/testing.go:1377 +0xdf
created by time.goFunc
        /usr/local/go/src/time/sleep.go:168 +0x44

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc0001cc900, 0x12218a4, 0x13, 0x12a0b28, 0x489fa6)
        /usr/local/go/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc0001cc800)
        /usr/local/go/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc0001cc800, 0xc000145dc0)
        /usr/local/go/src/testing/testing.go:909 +0xc9
testing.runTests(0xc00031e940, 0x1ba50a0, 0x8, 0x8, 0x0)
        /usr/local/go/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc0002e0f00, 0x0)
        /usr/local/go/src/testing/testing.go:1117 +0x176
main.main()
        _testmain.go:58 +0x135

goroutine 6 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x1baf8c0)
        /home/enorling/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
        /home/enorling/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0xd6

goroutine 8 [select, 9 minutes]:
github.com/Comcast/kuberhealthy/v2/pkg/checks/external.(*Checker).RunOnce(0xc000390480, 0x0, 0x0)
        /home/enorling/go/src/github.com/NissesSenap/kuberhealthy/pkg/checks/external/main.go:610 +0x1487
github.com/Comcast/kuberhealthy/v2/pkg/checks/external.TestExternalChecker(0xc0001cc900)
        /home/enorling/go/src/github.com/NissesSenap/kuberhealthy/pkg/checks/external/checker_test.go:78 +0xcf
testing.tRunner(0xc0001cc900, 0x12a0b28)
        /usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:960 +0x350

goroutine 34 [select, 9 minutes]:
github.com/Comcast/kuberhealthy/v2/pkg/checks/external.(*Checker).watchForCheckerPodShutdown(0xc000390480, 0xc0000512c0, 0x13b8d20, 0xc0003789c0)
        /home/enorling/go/src/github.com/NissesSenap/kuberhealthy/pkg/checks/external/main.go:376 +0x442
created by github.com/Comcast/kuberhealthy/v2/pkg/checks/external.(*Checker).RunOnce
        /home/enorling/go/src/github.com/NissesSenap/kuberhealthy/pkg/checks/external/main.go:573 +0x9dd

goroutine 15 [IO wait]:
internal/poll.runtime_pollWait(0x7fcf2d3b7fd0, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0003ec198, 0x72, 0x3f00, 0x3f6c, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0003ec180, 0xc0002d0000, 0x3f6c, 0x3f6c, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0003ec180, 0xc0002d0000, 0x3f6c, 0x3f6c, 0x203000, 0x0, 0x3f00)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000392148, 0xc0002d0000, 0x3f6c, 0x3f6c, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x68
crypto/tls.(*atLeastReader).Read(0xc000487260, 0xc0002d0000, 0x3f6c, 0x3f6c, 0x400, 0x400, 0xc000105970)
        /usr/local/go/src/crypto/tls/conn.go:780 +0x60
bytes.(*Buffer).ReadFrom(0xc0003233d8, 0x1389540, 0xc000487260, 0x40bd95, 0x10e9880, 0x11cd3e0)
        /usr/local/go/src/bytes/buffer.go:204 +0xb4
crypto/tls.(*Conn).readFromUntil(0xc000323180, 0x138a860, 0xc000392148, 0x5, 0xc000392148, 0x203000)
        /usr/local/go/src/crypto/tls/conn.go:802 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc000323180, 0x0, 0x0, 0xc000487220)
        /usr/local/go/src/crypto/tls/conn.go:609 +0x124
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0xc000323180, 0xc000404000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1255 +0x161
bufio.(*Reader).Read(0xc00039f1a0, 0xc00015c8f8, 0x9, 0x9, 0xc000105d10, 0x0, 0x8173d2)
        /usr/local/go/src/bufio/bufio.go:226 +0x26a
io.ReadAtLeast(0x13893e0, 0xc00039f1a0, 0xc00015c8f8, 0x9, 0x9, 0x9, 0xc000092040, 0x0, 0x1389660)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc00015c8f8, 0x9, 0x9, 0x13893e0, 0xc00039f1a0, 0x0, 0x0, 0xc00044bd40, 0x0)
        /home/enorling/go/pkg/mod/golang.org/x/net@v0.0.0-20190812203447-cdfb69ac37fc/http2/frame.go:237 +0x87
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00015c8c0, 0xc00044bd40, 0x0, 0x0, 0x0)
        /home/enorling/go/pkg/mod/golang.org/x/net@v0.0.0-20190812203447-cdfb69ac37fc/http2/frame.go:492 +0xa1
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000105fb8, 0x800a5d, 0xc0002ad3e0)
        /home/enorling/go/pkg/mod/golang.org/x/net@v0.0.0-20190812203447-cdfb69ac37fc/http2/transport.go:1679 +0x8c
golang.org/x/net/http2.(*ClientConn).readLoop(0xc00031af00)
        /home/enorling/go/pkg/mod/golang.org/x/net@v0.0.0-20190812203447-cdfb69ac37fc/http2/transport.go:1607 +0xa3
created by golang.org/x/net/http2.(*Transport).newClientConn
        /home/enorling/go/pkg/mod/golang.org/x/net@v0.0.0-20190812203447-cdfb69ac37fc/http2/transport.go:670 +0x62f

goroutine 23 [chan send, 9 minutes]:
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc0003f4780)
        /home/enorling/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/watch/streamwatcher.go:127 +0x15b
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
        /home/enorling/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/watch/streamwatcher.go:71 +0xbe

goroutine 70 [sleep]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:310
time.Sleep(0x12a05f200)
        /usr/local/go/src/runtime/time.go:105 +0x157
github.com/Comcast/kuberhealthy/v2/pkg/checks/external.(*Checker).waitForPodStatusUpdate.func1(0xc000390480, 0xc0000a6a80, 0x0, 0x0, 0x0)
        /home/enorling/go/src/github.com/NissesSenap/kuberhealthy/pkg/checks/external/main.go:740 +0xa4
created by github.com/Comcast/kuberhealthy/v2/pkg/checks/external.(*Checker).waitForPodStatusUpdate
        /home/enorling/go/src/github.com/NissesSenap/kuberhealthy/pkg/checks/external/main.go:731 +0xd8

goroutine 56 [chan send, 9 minutes]:
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc0003124c0)
        /home/enorling/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/watch/streamwatcher.go:127 +0x15b
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
        /home/enorling/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/watch/streamwatcher.go:71 +0xbe
FAIL    github.com/Comcast/kuberhealthy/v2/pkg/checks/external  600.012s
?       github.com/Comcast/kuberhealthy/v2/pkg/checks/external/checkclient      [no test files]
?       github.com/Comcast/kuberhealthy/v2/pkg/checks/external/status   [no test files]

**Comment by 2infinitee** [comment]
@NissesSenap I think there was already a issue opened for this and I'm actively working on it as well. https://github.com/Comcast/kuberhealthy/issues/353

**Comment by NissesSenap** [comment]
That is great!
Tried to search around but apparently but not good enough. Thanks @2infinitee , I will close this one.
