### ISSUE TITLE
kuberhealthy trying to fetch the image which doesn't exist

### ISSUE THREAD

**Issue by sbuvaneshkumar** [Comcast/kuberhealthy#420]
```
அ ~ helm fetch kuberhealthy/kuberhealthy

அ ~ tar xvf kuberhealthy-2.1.2.tgz; cd kuberhealthy

அ  kuberhealthy  ack -B 2 "tag: v2.1.2"
values.yaml
13-image:
14-  repository: kuberhealthy/kuberhealthy
15:  tag: v2.1.2

```
But we don't have a image with the tag: **v2.1.2** 🤷‍♂️
Reference: https://hub.docker.com/r/kuberhealthy/kuberhealthy/tags

Hence the failure:
```
  Warning  Failed     26m (x4 over 28m)      kubelet, minikube  Failed to pull image "kuberhealthy/kuberhealthy:v2.1.2": rpc error: code = Unknown desc = Error response from daemon: manifest for kuberhealthy/kuberhealthy:v2.1.2 not found: manifest unknown: manifest unknown
  Warning  Failed     26m (x4 over 28m)      kubelet, minikube  Error: ErrImagePull

```

**Comment by chadbitzer** [comment]
Thank you @sbuvaneshkumar, there is a bug with 2.1.2 and it's not pushing correctly to dockerhub.  We've reverted back to 2.1.0 and I just made the change to gh-pages.  It should replicate out to hub.helm.sh.  In the meantime, you should still be able to specify --version 2.1.0.

**Comment by chadbitzer** [comment]
Repo has been rolled back to 2.1.0 only.
