### ISSUE TITLE
Implement more fine grained tagging in prometheus metrics

### ISSUE THREAD

**Issue by mshutt** [Comcast/kuberhealthy#43]
**Describe the feature you would like and why you want it**

Add additional tags to prometheus check value metrics:

https://github.com/Comcast/kuberhealthy/blob/6dab3697e6626f1e76f3e3a2f3e4941524046f80/pkg/metrics/exporter.go#L40

e.g. check=$checkname,namespace=$namespace for additional grainularity.

**Additional context**

We're feeding these into DataDog such as:  https://photos.app.goo.gl/4o989E9uvSWkoVmd6

It would be excellent if we had per check/namespace tuples that we could filter on and use in alerts if a check value drops below 1.

**Comment by integrii** [comment]
@ihoegen did the Prometheus integration. He is off in Mexico on a honeymoon right now though...  I assigned him to this one.

**Comment by ihoegen** [comment]
The replace is there because for a little bit the name of the metric was the name of the check, and spaces made things tricky. Now it's just leftover code I could remove. I'll update it to parse that when I get back on Monday

**Comment by mshutt** [comment]
Right, but we don't want to remove the fidelity were getting there since
the podstatuscheck can execute for N namespaces same as the podhealthcheck

Right?  Just create a tuple of tags {check=type,namespace=namespace}

**Comment by ihoegen** [comment]
Yeah that makes sense. I'll remove the parsing of the spaces, and use the namespace field from the check object to populate that tuple

**Comment by ihoegen** [comment]
#56 addresses this
