### ISSUE TITLE
generate check pod ownerReference bug && a new way to delete khstate cr and check pod

### ISSUE THREAD

**Issue by calmkart** [Comcast/kuberhealthy#439]
**Describe the bug**
https://github.com/Comcast/kuberhealthy/blob/3309e2b740e635f00bcd257c5ba0be5209ddaed2/pkg/checks/external/util/main.go#L18-L35

now, generate a check pod's ownerReference is find the kuberhealhty pod's `os.Hostname()`

but in my cluster, the kuberhealthy pod name is not equal to `os.Hostname` in pod, so it will trigger a bug
https://github.com/Comcast/kuberhealthy/blob/3309e2b740e635f00bcd257c5ba0be5209ddaed2/pkg/checks/external/main.go#L1055-L1058

return error here and no check pod be created.

**Versions**
 - Kubernetes Version: v1.16.3-287
 - Kuberhealthy Release or build master

**Additional context**
```
➜  http-check git:(master-canary-check) ✗ kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
kuberhealthy-65cc744f64-kfz62   1/1     Running   0          72m
➜  http-check git:(master-canary-check) ✗ kubectl exec kuberhealthy-65cc744f64-kfz62 -it /bin/bash
kuberhealthy@kuberhealthy-011167090080:/app$ hostname
kuberhealthy-011167090080
```
kuberhealthy-65cc744f64-kfz62 != kuberhealthy-011167090080

And it is not a good logic to bind the ownerReference of the check pod to the pod of kuberhealthy.
I think that the ownerReference of check pod and khstate cr should point to the corresponding khcheck cr. When khcheck cr is deleted, the corresponding check pod and khstate cr are automatically cleared.
In this way, there is no need to use the timer to watch khcheck cr changes manually delete khstate.

**Comment by calmkart** [comment]
this issue should add a label `feature request`

**Comment by NissesSenap** [comment]
Dumb question but how do you create a pod that don't got the same hostname as podname? 
Is this something that was changed after 1.9.7? 
I haven't done anything interesting with such old version of k8s.

I definitely see your point in setting the owner to the khc instead.

**Comment by calmkart** [comment]
> Dumb question but how do you create a pod that don't got the same hostname as podname?
> Is this something that was changed after 1.9.7?
> I haven't done anything interesting with such old version of k8s.
> 
> I definitely see your point in setting the owner to the khc instead.
```
➜  http-check git:(master-canary-check) ✗ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.3-287", GitCommit:"47391eafa014ba63824c0c12477cf946ba9cafea", GitTreeState:"clean", BuildDate:"2020-04-01T07:38:15Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
```
Why does the hostname of my pod not equal to podname is not so important.

If we want to set the check pod's OwnerReference to kuberhealthy pod, we can get the podname here.

But I really do n’t think it ’s a good idea to set the OwnerReference of the check pod to kuberhealthy pod. Because the controlled object of the check pod should be khcheck cr, it is more reasonable to point to khcheck cr.

Sorry, if I have any offense, please forgive me.

**Comment by NissesSenap** [comment]
No I know it's not important I'm just curios and want to learn something I don't know :)

For sure, the reason why I used the hostname is because it's faster and simpler then talking to the k8s api but I didn't think of this edge case for sure.

I agree with you, let's see what the comcast guys say when they come online.

**Comment by joshulyne** [comment]
@calmkart do you think we can close this issue? i know you created a PR for this #438 and I believe we concluded that we didn't want the ownerReference to point to the khcheck, but back to the kuberhealthy pod. Super appreciative of the work/discussion you put into this and sorry we decided to go the other way!

**Comment by calmkart** [comment]
@joshulyne sorry for late reply, i'm I'm on vacation recently. 
i'll close this issue immediately.
Thanks for your notice.
