### ISSUE TITLE
namespace list regexp?

### ISSUE THREAD

**Issue by mshutt** [Comcast/kuberhealthy#44]
What would you all think about doing a regexp for namespace matching?  In a world where we have 100's of namespaces, I'd love to be able to throw a checker on each (if it can scale) for massively failing pods.  Obviously, this would be a query into the API to match namespaces that will be submitted as a check.

**Comment by integrii** [comment]
I think this is a good idea... but how would we configure it?  By a flag?  Environment variable? Hrmm... 

Maybe we could detect if there is a `*` and then change to prefix matching...

**Comment by mshutt** [comment]
I was thinking it could just be in the comma separated list of args, but we
would have to be cautious of regexps with commas ;)  or maybe we have anew
arg for a regexp match? It also means instantiating the api client in the
main thread before we create the checkers.

**Comment by integrii** [comment]
This kind of feature may fit nicely into a configmap as mentioned in #5

**Comment by lolimjake** [comment]
I'm starting work on #5 and I'll see if I can include this feature in that work, or at least add it in once the other framework is in place.

**Comment by integrii** [comment]
this one is now obsolete considering the `khcheck` pattern where `khcheck` resources are created in namespaces wherein checks should run
