### ISSUE TITLE
Another serious bug, the main process is blocked

### ISSUE THREAD

**Issue by calmkart** [Comcast/kuberhealthy#447]
**Describe the bug**
This bug is similar to #439 , but not the same, it is very tricky

How to reproduce this bug
1. create a khcheck cr
2. the khcheck  cr will create a kh check pod 
3. if the check pod keep containerCreating (any reason)
4. kuberhealhty pod main process blocked

Please note that although this bug looks similar to #439 , it is completely different. #439  bugs are complicated to troubleshoot, but simple to solve. This bug is very easy to reproduce, but it is more difficult to solve. Below I will explain in detail the cause of the bug.

If we make any changes to khcheck cr, the event will be monitored, and a channel is issued without distinguishing the event type
https://github.com/Comcast/kuberhealthy/blob/7572e86a2b433864bc7d647203496a8411ca5dc5/cmd/kuberhealthy/kuberhealthy.go#L295-L314
Then restart all khcheck
https://github.com/Comcast/kuberhealthy/blob/7572e86a2b433864bc7d647203496a8411ca5dc5/cmd/kuberhealthy/kuberhealthy.go#L195-L199
but in `k.StopChecks()` we should wait for all check pod shutdown
https://github.com/Comcast/kuberhealthy/blob/7572e86a2b433864bc7d647203496a8411ca5dc5/cmd/kuberhealthy/kuberhealthy.go#L122-L132

This time a bug appeared
Our pod has not started at all, it has been stuck in the containerCreating state, waitforstart () can not be completed, it is impossible to complete shutdown ()

How to fix this bug is worth thinking about. I think it is impossible to fix this kind of bug with the logic of restarting all khcheck by monitoring any changes at present. Because we can't judge whether the pod is in ContainerCreating, it is really dead or busy (for example, in pull image), so we can't kill these pods automatically when restarting, we can only wait for the pods to automatically recycle after the timeout period. In this process, the main process is stuck.

I think a good way to solve this kind of problem (or even other bugs) is to distinguish the type of khcheck change event that is monitored, and do different treatments for different types of events, instead of restarting the simple and rough monitoring events like now, including The processing of khstate is also rough.

Because I have a lot of differences in the scenes we use from the standard scenes (for example, we want to be able to support the callback logic for detecting multiple clusters), so I customized and modified the community version of Kuberhealthy, which has solved this bug (even Including other questions). But I am not sure whether this kind of pr that modify the monitoring mechanism can be accepted. (Maybe the kuberhealthy was designed this way for other reasons)

If I can, I am very willing to submit the changes to PR, but the process changes may be relatively large.

**Steps To Reproduce**
How to reproduce this bug
1. create a cr
2. the cr will create a kh check pod 
3. if the check pod keep containerCreating (any reason)
4. kuberhealhty pod main process blocked

**Comment by calmkart** [comment]
@integrii @jonnydawg
PTAL, thanks.
Looking forward to your reply

**Comment by calmkart** [comment]
For example, I think that watch.Added / watch.Modified / watch.Deleted does not need to restart all khcheck inspections. Just add a new inspection to the watch.Added event, and clean up the pod / watch.Deleted event. khstate (via ownerReference) will do. It is not that adding a khcheck x requires restarting khcheck abcdefg.
We can change the logic here like this (pseudo code)
```
 for khc := range watcher.ResultChan() { 
 	switch khc.Type { 
 	case watch.Added: 
 		log.Debugln("khcheck monitor saw an added event") 
                checker := khc.object.(*checkerType)
                go k.Runcheck(checker )
 	case watch.Modified: 
 		log.Debugln("khcheck monitor saw a modified event") 
 		checker := khc.object.(*checkerType)
                go k.RestartCheck(checker )
 	case watch.Deleted: 
 		log.Debugln("khcheck monitor saw a deleted event") 
 		checker := khc.object.(*checkerType)
                go k.removeCheck(checker )
 	case watch.Error: 
 		log.Debugln("khcheck monitor saw an error event") 
 		e := khc.Object.(*metav1.Status) 
 		log.Errorln("Error when watching for khcheck changes:", e.Reason) 
 		break 
 	default: 
 		log.Warningln("khcheck monitor saw an unknown event type and ignored it:", khc.Type) 
 	} 
 } 
```
If so, I think `go notifyChanLimiter(maxUpdateInterval, externalChecksUpdateChan, externalChecksUpdateChanLimited)` is no longer needed

**Comment by integrii** [comment]
I really appreciate the very detailed description of this issue and I am very impressed at how closely you have been testing Kuberhealthy.  We are all better for your hard work - thanks!

I think the easiest way to solve this is to wrap the blocking code in `select` logic that makes it time out after some period of time.  If the timeout is reached in the `select` statement, then we force remove all existing resources, wait some period of time, then just continue with normal operation.  

Does that sound like a good solution to you?

I prefer to keep the full delete and reload everything logic in place for all event types because it is very thorough.  It is hard to consider all the ways a small change can affect things, so I prefer to just rebuild on all changes.

Do you work for Alibaba?  If so, we would really like to start filling out a list of adopters [here](https://github.com/Comcast/kuberhealthy/blob/master/docs/KUBERHEALTHY_ADOPTERS.md) and would appreciate a PR with your info!

Let me know what you think about wrapping the broken code in a `select` that results in force deletion.

**Comment by calmkart** [comment]
> I really appreciate the very detailed description of this issue and I am very impressed at how closely you have been testing Kuberhealthy. We are all better for your hard work - thanks!
> 
> I think the easiest way to solve this is to wrap the blocking code in `select` logic that makes it time out after some period of time. If the timeout is reached in the `select` statement, then we force remove all existing resources, wait some period of time, then just continue with normal operation.
> 
> Does that sound like a good solution to you?
> 
> I prefer to keep the full delete and reload everything logic in place for all event types because it is very thorough. It is hard to consider all the ways a small change can affect things, so I prefer to just rebuild on all changes.
> 
> Do you work for Alibaba? If so, we would really like to start filling out a list of adopters [here](https://github.com/Comcast/kuberhealthy/blob/master/docs/KUBERHEALTHY_ADOPTERS.md) and would appreciate a PR with your info!
> 
> Let me know what you think about wrapping the broken code in a `select` that results in force deletion.

In the modified version, I did this (because in my usage scenario, I will not modify the khcheck configuration, only add and delete two types of operations, so I skipped the modify event, in fact, the modify event triggers the restart of the current check. )

```
for khc := range watcher.ResultChan() {
	switch khc.Type {
	case watch.Added:
		log.Debugln("khcheck monitor saw an added event")
		// run the new check
		checker := k.khcheckCrdToChecker(khc.Object.(*khcheckcrd.KuberhealthyCheck))
		go k.runCheck(ctx, checker)
	case watch.Modified:
		log.Debugln("khcheck monitor saw a modified event")
		c <- struct{}{}
	case watch.Deleted:
		log.Debugln("khcheck monitor saw a deleted event")
		go k.deleteRelatedKhstate(*khc.Object.(*khcheckcrd.KuberhealthyCheck))
	case watch.Error:
		log.Debugln("khcheck monitor saw an error event")
		e := khc.Object.(*metav1.Status)
		log.Errorln("Error when watching for khcheck changes:", e.Reason)
		break
	default:
		log.Warningln("khcheck monitor saw an unknown event type and ignored it:", khc.Type)
	}
}
```

Setting the timeout in select can indeed fix this bug, but it always feels unnatural. For example, how appropriate is the timeout setting? Is it possible for a pod to pull the image slowly and then be killed unnecessarily? In fact, in the process of waiting for the timeout, the main process is still stuck.

In addition, from my logical judgment, I think that if we do add / delete / modify to a certain khcheck, it should not affect other khcheck. For example, for khcheck A, we set the period to 60m, and then at a certain moment, khcheck A just ran once. After 1 minute, we modified khcheck B in the cluster. At this time, khcheck A will also run once. Doesn't the cycle of khcheck A change? This problem is especially obvious in scenarios where we frequently adjust khcheck in the cluster.

I work in alibaba, and currently in some test environment, I can explore whether we can realize our internal inspection scene through kuberhealthy, but it is only exploring. I made some modifications to kuberhealthy, mainly to fix some bugs and support single inspection (non-periodical) and multi-cluster unified callback reporting (the usage scenario may be different from the community version, the current community version seems to only support multi-cluster Can poll khstate). If subsequent kuberhealthy can really be put into use internally, it may be more appropriate to add adopters. (I can't decide this)

I will try to mention a few prs to add some support, whether it is reasonable under your review. (May not be very fast, because there is other work to be done)

Thank you for your patient reply, thank kuberhealthy this interesting tool, looking forward to more discussion.

**Comment by joshulyne** [comment]
Closing as I believe #540 addressed this issue. @calmkart please feel free to submit another issue if you still see this as a problem!
