### ISSUE TITLE
Document all injected environment variables on checker pods

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#450]
We should add `KH_CHECK_RUN_DEADLINE` to [this doc](https://github.com/Comcast/kuberhealthy/blob/master/docs/EXTERNAL_CHECK_CREATION.md) along with all the other environment variables that are loaded into pods by KH by default.

**Comment by bavarianbidi** [comment]
have to rework PR #443 and could add this in my PR if you want?

**Comment by integrii** [comment]
Sure!  Up to you.  I tend not to keep adding into PRs because things go wrong and the extraneous changes get dropped by accident.  More smaller PRs is normally better practice, I think.

Either way is fine here, though.

**Comment by jonnydawg** [comment]
All the crucial ones are documented (all the ones check implementers should be aware about)
