### ISSUE TITLE
Check for null errorMessages when reporting failure back to Kuberhealthy 

### ISSUE THREAD

**Issue by joshulyne** [Comcast/kuberhealthy#453]
In the external checkClient package, we should verify the errorMessage being sent by external checks before reporting the failure back to Kuberhealthy.

**Comment by integrii** [comment]
Additionally, the handler within Kuberhealthy should intelligently check if a `null` was passed in (after json unmarshalling) and replace the `null` with a `[]string`

**Comment by jdowni000** [comment]
submitted PR `https://github.com/Comcast/kuberhealthy/pull/468` to address null error message.

**Comment by 2infinitee** [comment]
PR has been merged, closing issue.
