### ISSUE TITLE
Many of the external check registry link are invalid

### ISSUE THREAD

**Issue by bbhenry** [Comcast/kuberhealthy#460]
Many links from https://github.com/Comcast/kuberhealthy/blob/master/docs/EXTERNAL_CHECKS_REGISTRY.md are hitting 404 page not found error. Please update the documentation so we can take advantage of those checks. Thanks in advance.

**Comment by joshulyne** [comment]
@bbhenry thanks for pointing this out! Will make sure to get a fix in for this.

**Comment by jonnydawg** [comment]
Thanks for bringing this up!
