### ISSUE TITLE
Question: why is pod-restarts and pod-status disabled by default in ver. 2

### ISSUE THREAD

**Issue by bbhenry** [Comcast/kuberhealthy#466]
Migrating from Kuberhealthy 1 to 2, I've noticed that pod-restarts and pod-status are not enabled by default. What's the reasoning behind this change? I've also notice they are missing the `Service Account Name` `podSpec`. I'd get permission errors for the checks because they inherited the `default` Service Account Name in the namespace they were applied.

**Comment by integrii** [comment]
Moving from KH 1 to 2 is a pretty large change.  In v1, Kuberhealthy checks ran as part of the main `kuberhealthy` binary.  In v2, checks are scheduled as their own pods that report back to kuberhealthy over HTTP.  We had to make a lot of changes to code and behavior to pull this off.

If you want to set a `serviceAccountName`, you just need to put it in the `podSpec` section of the `khcheck` (`kubectl get khcheck`).

Having the pod-restarts and pod-status checks disabled by default probably wasn't a design decision - it probably just got over looked or those checks weren't stable enough on the original release of v2.  You can of course re-enable them by creating a `khcheck` again.

Here are the check pages for those:
 https://github.com/Comcast/kuberhealthy/tree/master/cmd/pod-restarts-check
https://github.com/Comcast/kuberhealthy/tree/master/cmd/pod-status-check

Keep in mind that you must put one `khcheck` in every namespace that you want to run your checks.

**Comment by bbhenry** [comment]
@integrii That's exactly what I did. I've created khcheck manifest files for pod-restarts and pod-status. Like you mentioned, if things are meant to be decoupled from the kuberhealthy core, maybe we should removed all of the checks from helm chart then? Are the pod-status and pod-restarts check now considered stable for V2?

**Comment by integrii** [comment]
Sorry for the late reply here.  Yes, all checks are stable for version 2.  Version 1 actually didn't have external checks at all!

I thought about removing all checks from the helm chart, but new users would have to figure out that no checks were running on first install - so I feel like giving them a starting point is useful.
