### ISSUE TITLE
deployment check is fixated to check kuberhealthy namespace

### ISSUE THREAD

**Issue by bbhenry** [Comcast/kuberhealthy#467]
**Describe the bug**
Deploying kuberhealthy following the helm instruction and set the namespace to ie. `demo`. Installation went fine and all resources were created in the `demo` namespace. But when you check the khstate of `deployment` , you'll see the logs still trying to do the test in kuberhealthy namespace instead of the designated one. 

```
time="2020-05-05T09:55:52Z" level=info msg="Performing check in kuberhealthy namespace."
time="2020-05-05T09:55:52Z" level=info msg="Parsed CHECK_DEPLOYMENT_REPLICAS: 4"
time="2020-05-05T09:55:52Z" level=info msg="Parsed CHECK_TIME_LIMIT: 900"
time="2020-05-05T09:55:52Z" level=info msg="Check time limit set to: 15m0s"
time="2020-05-05T09:55:52Z" level=info msg="Parsed CHECK_DEPLOYMENT_ROLLING_UPDATE: true"
time="2020-05-05T09:55:52Z" level=info msg="Check deployment image will be rolled from [nginx:1.17.8] to [nginx:1.17.9]"
time="2020-05-05T09:55:52Z" level=info msg="Kubernetes client created."
time="2020-05-05T09:55:52Z" level=info msg="Starting check."
time="2020-05-05T09:55:52Z" level=info msg="Wiping all found orphaned resources belonging to this check."
time="2020-05-05T09:55:52Z" level=info msg="Attempting to find previously created service(s) belonging to this check."
time="2020-05-05T09:55:52Z" level=info msg="Error listing services: services is forbidden: User \"system:serviceaccount:demo:deployment-sa\" cannot list resource \"service
s\" in API group \"\" in the namespace \"kuberhealthy\""
time="2020-05-05T09:55:52Z" level=warning msg="Failed to find previous service: services is forbidden: User \"system:serviceaccount:demo:deployment-sa\" cannot list resour
ce \"services\" in API group \"\" in the namespace \"kuberhealthy\""
time="2020-05-05T09:55:52Z" level=info msg="Attempting to find previously created deployment(s) belonging to this check."
time="2020-05-05T09:55:52Z" level=info msg="error listing deployments: deployments.apps is forbidden: User \"system:serviceaccount:demo:deployment-sa\" cannot list resourc
e \"deployments\" in API group \"apps\" in the namespace \"kuberhealthy\""
time="2020-05-05T09:55:52Z" level=warning msg="Failed to find previous deployment: deployments.apps is forbidden: User \"system:serviceaccount:demo:deployment-sa\" cannot
list resource \"deployments\" in API group \"apps\" in the namespace \"kuberhealthy\""
time="2020-05-05T09:55:52Z" level=info msg="Successfully cleaned up prior check resources."
time="2020-05-05T09:55:52Z" level=info msg="Creating deployment resource with 4 replica(s) in kuberhealthy namespace using image [nginx:1.17.8] with environment variables: map[]"
time="2020-05-05T09:55:52Z" level=info msg="Creating container using image [nginx:1.17.8] with environment variables: map[]"
time="2020-05-05T09:55:52Z" level=info msg="Created deployment resource."
time="2020-05-05T09:55:52Z" level=info msg="Creating deployment in cluster with name: deployment-deployment"
time="2020-05-05T09:55:52Z" level=info msg="Failed to create a deployment in the cluster: deployments.apps is forbidden: User \"system:serviceaccount:demo:deployment-sa\"
cannot create resource \"deployments\" in API group \"apps\" in the namespace \"kuberhealthy\""
time="2020-05-05T09:55:52Z" level=error msg="error occurred creating deployment in cluster: deployments.apps is forbidden: User \"system:serviceaccount:demo:deployment-sa\
" cannot create resource \"deployments\" in API group \"apps\" in the namespace \"kuberhealthy\""
time="2020-05-05T09:55:52Z" level=error msg="Reporting errors to Kuberhealthy: [deployments.apps is forbidden: User \"system:serviceaccount:demo:deployment-sa\" cannot cre
ate resource \"deployments\" in API group \"apps\" in the namespace \"kuberhealthy\"]"
```

**Steps To Reproduce**
```
kubectl create namespace demo
kubectl config set-context --current --namespace=demo
helm repo add kuberhealthy https://comcast.github.io/kuberhealthy/helm-repos
helm upgrade --install kuberhealthy kuberhealthy/kuberhealthy --namespace demo
```

**Expected behavior**
Expected the check states to all pass without permission errors.

**Screenshots**
n/a

**Versions**
 - Kubernetes Version: v1.15.9
 - Kuberhealthy v2.1.0

**Comment by jonnydawg** [comment]
The deployment check defaults to use the `kuberhealthy` namespace, but can be configured to check a different namespace via environment variable `CHECK_NAMESPACE`. Please check out https://github.com/Comcast/kuberhealthy/blob/master/cmd/deployment-check/README.md.

There currently is not a way to specify this via Helm yet, and I am looking into a fix for that.

**Comment by jonnydawg** [comment]
It seems like you can add this flag to your `helm` command to modify the `deployment check`'s operating namespace: `--set check.deployment.extraEnvs.CHECK_NAMESPACE=demo`

```
helm upgrade --install kuberhealthy kuberhealthy/kuberhealthy --namespace demo --set check.deployment.extraEnvs.CHECK_NAMESPACE=demo
```

**Comment by jonnydawg** [comment]
After further consideration, maybe the deployment check should default to using the namespace that the CRD lives in.

**Comment by bbhenry** [comment]
@jonnydawg I'll get the environment variable a try, thank you. 

CRD is global resource in k8s, did you mean to say RBAC policies? (roles, user, and rolebindings?) I think the deployment check should default to where the RBAC permission is created with helm, in my case, the `demo` namespace.

**Comment by jonnydawg** [comment]
I was talking about the `khcheck` CRD -- that should be namespaced.

Let me know if that flag works for you!

**Comment by bbhenry** [comment]
> It seems like you can add this flag to your `helm` command to modify the `deployment check`'s operating namespace: `--set check.deployment.extraEnvs.CHECK_NAMESPACE=demo`
> 
> ```
> helm upgrade --install kuberhealthy kuberhealthy/kuberhealthy --namespace demo --set check.deployment.extraEnvs.CHECK_NAMESPACE=demo
> ```

@jonnydawg The `extraEnvs.CHECK_NAMESPACE=demo` worked! 
And yes, I do think the check should be defaulted to the namespace the khcheck is being applied.

**Comment by bavarianbidi** [comment]
hi @bbhenry 
i created PR #461 which may solve your problem

**Comment by jonnydawg** [comment]
This check should, by-default now operate in the same namespace that the `khcheck` lives in!

**Comment by bbhenry** [comment]
> This check should, by-default now operate in the same namespace that the `khcheck` lives in!

Thank you. How long does the change take to make it into the `master` helm chart?

**Comment by jonnydawg** [comment]
We're waiting to update the chart with our next release -- which should hopefully be soon! There are still some changes and updates that are undergoing testing and review right now!
