### ISSUE TITLE
KH_CHECK_RUN_DEADLINE environment variable required in latest test-external-check, but not defined in KH 2.1.0. 

### ISSUE THREAD

**Issue by zjhans** [Comcast/kuberhealthy#472]
**Describe the bug**
Running kuberhealthy/test-external-check:latest crashes test pod. Version requires environment variable KH_CHECK_RUN_DEADLINE which is undefined currently. 

Additionally, error message in logs needs formatting fix, spaces are missing around the variable name in the error.

Logs:
2020/05/12 17:27:43 checkClient: ERROR: kuberhealthy check deadline from environment variableKH_CHECK_RUN_DEADLINEwas blank

**Steps To Reproduce**
- Run the KH check using image _kuberhealthy/test-external-check:latest_ instead of _v1.2.1_ or earlier.
- Check failed pods log for above error

**Expected behavior**
All published versions of the test check should work if properly configured.

**Versions**
 - Cluster OS: Docker Desktop
 - Kubernetes Version: 1.16.6
 - Kuberhealthy Release 2.1.0

**Comment by jonnydawg** [comment]
Yes, thanks for noticing this! The test check and deployment check were updated preemptively for the 2.2.0 release.

**Comment by jonnydawg** [comment]
The update to the test external check should no longer fatal!
