### ISSUE TITLE
Pod eviction only looking for Running pods when cleaning up KH checks, leading to potential memory usage issues.

### ISSUE THREAD

**Issue by zjhans** [Comcast/kuberhealthy#473]
**Describe the bug**
Pod eviction currently appears to only target pods tagged with a status.phase=Running. This can lead to continuous spawning of pods with a status of ImagePullBackOff or another error state, resulting in a node crash due to resource/memory usage.

Logs:
time="2020-05-12T17:18:17Z" level=info msg="c2f17ef8-f86f-4e7f-9a42-ff045d96a672 kuberhealthy/kh-external-test-check: [eviction: looking for pods with the label kuberhealthy-check-name = kh-external-test-check and status.phase=Running]"

**Steps To Reproduce**
- Deploy a test check that will intentionally fail (I.e., point to a repository that does not exist, set ImagePullPolicy to Always
- Leave the khcheck active, failed pods will continue to accumulate.

**Expected behavior**
I believe all old, unneeded pods for the khcheck in question should be evicted.

**Screenshots**
[Uploading image.png…]()

**Versions**
 - Cluster OS: Docker Desktop
 - Kubernetes Version: 1.16.6
 - Kuberhealthy Release 2.1.0

**Comment by jonnydawg** [comment]
Thanks for bringing this up! There have been reports of memory leaks, but we have not been able to reproduce it.

**Comment by zjhans** [comment]
Original image failed to upload.

![image](https://user-images.githubusercontent.com/55612469/81934462-fbda4f00-95bc-11ea-9a19-62623c3f2fcb.png)
