### ISSUE TITLE
Helm chart doesn't exists

### ISSUE THREAD

**Issue by bbkgh** [Comcast/kuberhealthy#497]
Hi. Kuberhealthy helm chart doesn't exists in expected location.

**Steps To Reproduce**
- helm repo add kuberhealthy https://comcast.github.io/kuberhealthy/helm-repos
- helm repo update
- helm fetch kuberhealthy/kuberhealthy
result : Error: Failed to fetch https://comcast.github.io/kuberhealthy/kuberhealthy-2.2.0.tgz : 404 Not Found

**Comment by chadbitzer** [comment]
@bbkgh this issue is being addressed in pr #499.

**Comment by chadbitzer** [comment]
@bbkgh this is fixed and tested.
`helm install kuberhealthy kuberhealthy/kuberhealthy`
