### ISSUE TITLE
Allow check intervals to be configured by the user

### ISSUE THREAD

**Issue by lolimjake** [Comcast/kuberhealthy#5]
Check intervals are currently hard coded, we should change to user controlled check intervals.

**Comment by integrii** [comment]
We may want to add and use a configmap.  I feel like the number of tweakable options is going to increase steadily over time.

**Comment by lolimjake** [comment]
Going to start working up a configmap model

**Comment by lolimjake** [comment]
Though, looking at  #143 proposed use of CRD/operator model for checks, perhaps the original suggestion to use a CRD for the included kuberhealthy flags is the direction we want to move for this proposal, too @integrii

**Comment by integrii** [comment]
`runInterval` is configurable in the new khcheck resource!
