### ISSUE TITLE
Include Namespace as Part of Check Details

### ISSUE THREAD

**Issue by ihoegen** [Comcast/kuberhealthy#50]
**Describe the solution you would like to see happen**

 This proposal is to include the check's namespace as part of the CheckDetails, which in turn goes into the State.

The main benefit to including the namespace as part of the CheckDetails is that it allows for more fine-grained metrics.

 By having the namespace as part of CheckDetails, it is possible to include namespace as a label in the prometheus metric, allowing for greater flexibility in dashboards.

**How do you propose we build it?**
To do this, the CheckDetails struct would need to be updated to include the check namespace, possibly even include the name. These fields would then become part of the CRD when it's created.

**Comment by integrii** [comment]
I think this is okay.  It looks like it is required for #44.  This mean making one CRD object for each namespace that each check runs, I think.

**Comment by integrii** [comment]
@ihoegen you added this in your prior change that was merged, correct?

**Comment by ihoegen** [comment]
Yep
