### ISSUE TITLE
helm installation broken

### ISSUE THREAD

**Issue by nstott** [Comcast/kuberhealthy#501]
**Describe the bug**
Helm installation instructions do not work

**Steps To Reproduce**
following the helm installation instructions does not work

```
helm repo add kuberhealthy https://comcast.github.io/kuberhealthy/helm-repos
Error: looks like "https://comcast.github.io/kuberhealthy/helm-repos" is not a valid chart repository or cannot be reached: failed to fetch https://comcast.github.io/kuberhealthy/helm-repos/index.yaml : 404 Not Found
```

If I try the new chart location I can add the repository

```
helm repo add kuberhealthy https://comcast.github.io/kuberhealthy/helm-repos/kuberhealthy-2.1.0/
"kuberhealthy" has been added to your repositories
```

but I am unable to fetch the chart
```
helm fetch kuberhealthy/kuberhealthy                                                            
Error: failed to fetch https://comcast.github.io/kuberhealthy/helm-repos/kuberhealthy-2.1.0/kuberhealthy/kuberhealthy-2.1.0.tgz : 404 Not Found
```

**Expected behavior**

everything just works

**Versions**
kube 1.14, 
helm 3

**Comment by integrii** [comment]
This should be fixed now!  A last minute helm chart publish got mixed up and we just fixed it.  Thank you for reporting this.

**Comment by nstott** [comment]
can confirm, thanks for the quick fix!
