### ISSUE TITLE
Add priorityClassName to helm chart for kuberhealthy deployment

### ISSUE THREAD

**Issue by mitchellmaler** [Comcast/kuberhealthy#517]
**Describe the feature you would like and why you want it**
Currently there is no option to add priorityClassName to the kuberhealthy deployment in the helm chart.

**Comment by joshulyne** [comment]
@mitchellmaler this should be a simple feature to add! 👍 we'll get on it!

**Comment by joshulyne** [comment]
#530 has been merged into master!
