### ISSUE TITLE
Support manual trigger for checks

### ISSUE THREAD

**Issue by FraBle** [Comcast/kuberhealthy#528]
**Describe the feature you would like and why you want it**
While the current implementation of kuberhealthy supports the continuous validation of K8s components and app, it would be nice to be able to manually trigger a check, e.g. after a deployment of an app to K8s.  

**Additional context**
We're currently evaluating to use kuberhealthy for service validations. While there are examples of how to create simple HTTP code/response content check, we want to take it to the next level and run HTTP API test suites. These should continuously run (already supported by kuberhealthy), but also be triggered manually in our deployment pipelines after a deployment rolled out for a specific app (this feature request).

**Comment by joshulyne** [comment]
@FraBle this seems like a good feature for us to take on! Thinking through the possible implementation and wondering if we should create a new custom resource, like `khjob` and have the check operate like a manually triggered k8s job and ensure that this `khjob` state gets reported back instead of a `khstate`

**Comment by FraBle** [comment]
Yeah, the use case is pretty close to what a traditional K8s Job does, so reporting back directly to the `khjob` (or equivalent) makes sense. I wonder if it would be possible though to combine this with the existing `khcheck` to avoid duplication: the same validations that run continuously should also be able to get triggered after an app deployment.

**Comment by joshulyne** [comment]
Going to take an initial stab at this feature! The plan is to create a new CRD `khjob` which kuberhealthy watches for and triggers when the `khjob` resource is applied. This `khjob` reports back to kuberhealthy and a `khstate` for the `khjob` is also captured. In the `khstate` we add a `"KuberhealthyJob"` boolean to indicate that this `khstate` object is from a `khjob`

**Comment by FraBle** [comment]
@joshulyne That sounds good to me. Thank you for picking it up! 🚀

**Comment by linkvt** [comment]
Hi @joshulyne , thanks for picking this up! I just wanted to ask how you are doing with this issue as I'm also interested in this feature. Please let me know how I can support here if possible.

**Comment by joshulyne** [comment]
hi @linkvt! so sorry it's been taking forever to merge PR #584 D: the tag says 2.4 release, but we're actually aiming for 2.3 as this PR is pretty much ready to be merged. We're soak testing it now in our own clusters! Feel free to pull down the `khjob` branch and test out the khjob feature, if you'd like! That'd be super helpful. I believe theres a docs/external_khjob.md file that explains how to implement the khjobs. Let me know how it works for you!
