### ISSUE TITLE
change deployment and deamonset images at airgapped environments

### ISSUE THREAD

**Issue by gorkemozlu** [Comcast/kuberhealthy#541]
hi

appreciate your work done here.

I'm using an airgapped kubernetes environment and changed main images that app uses. I've edited the helm template output with our internal container registry.
But berhealthy creates its own deployment and daemonset but the pods go imagepullbackoff because there is no connection to internet. 
I'ven through the codes but i could not find the correct files to modify them. How can we change those images  ? 

Thank you.

edit:
I've been through again found my answer. 
https://github.com/Comcast/kuberhealthy/tree/master/cmd/daemonset-check

**Comment by joshulyne** [comment]
@gorkemozlu closing this issue for now since it seems like you were able to solve it :) feel free to submit another issue if you run into another something else!
