### ISSUE TITLE
Add nodeSelector option to deployment-check podSpec

### ISSUE THREAD

**Issue by zeleena** [Comcast/kuberhealthy#547]
**Add nodeSelector option to deployment-check podSpec**
Currently, the deployment-check will fail in a cluster with both Linux nodes and Windows nodes. The deployment-check creates a deployment with pods that run CHECK_IMAGE, a Linux image. Since the Linux image CHECK_IMAGE will schedule on Windows nodes, and there is no nodeSelector to prevent this, it will fail since Windows nodes can't run Linux containers.
Note: this is different but the same underlying problem as #546, except with the **deployment** check.

**Insufficient workarounds**
While it is true we could taint the Windows nodes and add a toleration, having the functionality to use the nodeSelector within the deployment-check's podSpec would be highly preferable so that this node taint does not affect other deployments in the cluster.

**Desired change**
This change would include adding a field for NodeSelector under the deployment's .spec.template.spec (a key within this podSpec block: https://github.com/Comcast/kuberhealthy/blob/v2.2.0/cmd/deployment-check/deployment.go#L88 )

To grab the nodeSelector key(s) and value(s), it should be configurable in the [values file](https://github.com/Comcast/kuberhealthy/blob/v2.2.0/deploy/helm/kuberhealthy/values.yaml). I was thinking it could either inherit the [current nodeSelector configuration of the primary deployment-check pod](https://github.com/Comcast/kuberhealthy/blob/v2.2.0/deploy/helm/kuberhealthy/values.yaml#L84), or be set with extra environment variables via the [extraEnvs key](https://github.com/Comcast/kuberhealthy/blob/v2.2.0/deploy/helm/kuberhealthy/values.yaml#L80).

**Why this is important**
This is an issue because kuberhealthy will report "OK": false for the deployment-check with error:
```
failed to create deployment within timeout
```
since Linux containers can't be ran on Windows nodes. Without the nodeSelector, I do not want to run the deployment-check (but would like to) since it currently reports misleading information about my cluster.

**Comment by integrii** [comment]
Just like #546, we should do the following here:

- Add an environment variable to the helm chart for deployment check (maybe NODE_SELECTOR)
- Document the new environment variable in the README.md for the deployment check
- Read the environment variable into a global within the deployment check
- If the environment variable read is not blank (""), then set the node selector in the deployment spec that the pod creates
- Rev the deployment check version in both the makefile and helm chart

**Comment by jonnydawg** [comment]
This has been addressed in a PR and is undergoing testing and debugging.
