### ISSUE TITLE
Trigger kuberhealthy checks as part of a CI pipeline

### ISSUE THREAD

**Issue by linkvt** [Comcast/kuberhealthy#561]
Thanks for the nice project, I also think that those kind of synthetic tests will grow more and more to as they cannot really be replaced by simple metrics and as k8s admins need to know when some a basic use case is broken.

**Describe the feature you would like and why you want it**
I was thinking on how we could include kuberhealthy in our CI pipeline for our Kubernetes clusters which deploys almost everything including namespaces with rolebindings, the nvidia GPU operator or also a CSI plugin.
My goal is to have an automated rollout after a merged pull request from INT to PROD with end-to-end tests in-between as a gatekeeper for the PROD deployment.

**Additional context**
The simplified setup consists of a DEV, an INT and a PROD Kubernetes cluster.
The development flow would look like this:
1. A feature branch in our version control system is created
2. All changes on that branch are directly deployed in our DEV environment
3. Development is done including tests on DEV
4. Pull request from feature branch to master is opened
5. Pull request compares and applies the changes in a dry run to INT but doesn't deploy on INT 
6. Pull request is reviewed, approved and merged to master
7. CI sees new changes on master and triggers INT deployment
8. **CI INT deployment runs, finishes applying and triggers all kuberhealthy checks blocking (fails when kuberhealthy fails)**
9. Depending on the kuberhealthy check result the PROD rollout is triggered 

This is only a simplified idea, I would also have a pretty clean DEV environment also running kuberhealthy, but the important points for me are to 
- deploy automatically to PROD with no manual intervention
- and have kuberhealthy as a gatekeeper for this.

Any ideas if this could be done already now (didn't find anything for triggering all checks)?

Thanks!

**Comment by jonnydawg** [comment]
Related to #528

**Comment by integrii** [comment]
I am closing this one as a duplicate.  Please watch #528 for details because @joshulyne is working on this one soon I think.
