### ISSUE TITLE
Allow permissions in target namespace for pod-status check

### ISSUE THREAD

**Issue by zeleena** [Comcast/kuberhealthy#580]
**Describe the bug**
The pod-status check has the option to set the `TARGET_NAMESPACE` environment variable which ideally will perform the pod-status check in that namespace. However, the ServiceAccount does not have permissions to that `TARGET_NAMESPACE` if it is different than the release namespace. This may be because the RoleBinding for the ServiceAccount defaults to the release namespace instead of the target namespace, even though the RoleBinding should live in the namespace (the target namespace) that gives the account permissions to view.

Here's where the RoleBinding defaults to the release namespace rather than the target namespace: https://github.com/Comcast/kuberhealthy/blob/master/deploy/helm/kuberhealthy/templates/khcheck-pod-status.yaml#L51

**Steps To Reproduce**
Enable the pod-status check and under .Values.check, have the following for podStatus (we want our target namespace to be kube-system, but this can likely be set to any other namespace than the release namespace):
```
podStatus:
  enabled: true
  extraEnvs:
    TARGET_NAMESPACE: "kube-system"
```

The status page gives the following error (extra info redacted):
```
{
  "OK": false,
  ...
  "CheckDetails": {
    "kuberhealthy/pod-status": {
      "OK": false,
      "Errors": [
        "pods is forbidden: User \"system:serviceaccount:kuberhealthy:pod-status-sa\" cannot list resource \"pods\" in API group \"\" in the namespace \"kube-system\""
      ],
      ... }
  },
}
```

**Expected behavior**
The check should not have this permissions error, and the pod-status-sa service account should have access to the target namespace, even if it is different than the release namespace.

Two possible solutions may include:
1. Modify the khcheck-pod-status template's RoleBinding to live in the target namespace instead of the release namespace: https://github.com/Comcast/kuberhealthy/blob/master/deploy/helm/kuberhealthy/templates/khcheck-pod-status.yaml#L51
2. Allow passing in the name of the service account so that we can create our own service account with our own role binding with access to the target namespace. Right now, the service account is locked in by the template. The previous solution would be better since it doesn't require manual fixes for using the target namespace feature.

**Versions**
 - Kuberhealthy Chart version 2.2.0
 - Deployment image version 2.3.0
 - Pod Status check image version 1.2.2

**Comment by integrii** [comment]
Hey Zeleena.  Welcome back!

The checks included with the Helm chart aren't really meant to be highly customizable.  You'll notice that most checks aren't mentioned in that chart at all.  Rather, those checks are meant to make getting started with some basic checks easier.

If you would like to customize the check more than what the current helm chart allows, I would suggest changing `enabled: false` on the check in the helm chart, then hand-crafting a `khcheck` (or `khchecks`) that you want to run.  Perhaps wrap them in some other kind of automation that knows how to deploy the helm chart, then apply the static specs that you need... Maybe you could create another meta-chart that has subcharts for kuberhealthy and your checks.

The documentation for each specific check lives beside it in the codebase and is documented in the `README.md` for it.  For the pod status check, that lives [here](https://github.com/Comcast/kuberhealthy/tree/master/cmd/pod-status-check).
