### ISSUE TITLE
Add jobs to check-reaper

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#592]
The [check reaper](https://github.com/Comcast/kuberhealthy/tree/master/cmd/check-reaper) current purges checks that have run.

With the new addition of a `khjob` CRD, we will have a new class of pods to clean up.  See issue #528 for details.

We need to modify the check-reaper to:
- identify which things are jobs (and not khchecks)
- be sure the existing logic does not delete jobs
- decide when to delete pods created by a `khjob`
- implement the deletion code that actually deletes the job pods

Pod labels are normally used to identify metadata about a pod (like if its been spawned due to a job run or check run)

**Comment by integrii** [comment]
Waiting on issue #528

**Comment by jdowni000** [comment]
this was done with PR #692
