### ISSUE TITLE
Support for newer versions of Kubernetes

### ISSUE THREAD

**Issue by ewohltman** [Comcast/kuberhealthy#616]
Hello,

Currently, the `README.md` for the repo says "Kuberhealthy is currently tested on Kubernetes `1.9.x` to `1.15.x`."

Is Kuberhealthy consistently tested and maintained with new versions of Kubernetes as they are released?

**Comment by integrii** [comment]
We definitely should bump the supported version.  To do that, we just need to update the KinD tests to the newest label.  @chadbitzer should be able to take a look at this.

**Comment by ewohltman** [comment]
@integrii @chadbitzer Thanks very much for looking into this so quickly!

I see this issue seems to be tied to the `v2.4 Release` Project but the PR is tied to the `v2.3 Release` project. Not sure if they are supposed to be different, but if not this could be another checkbox on the road to `v2.3 Release` :tada: 

Thanks again!

**Comment by integrii** [comment]
i just saw this run today with kube 1.18... we should update the readme to indicate the new version support. reopening

**Comment by chadbitzer** [comment]
Completed in previous PR
