### ISSUE TITLE
Parameterize PodDisruptionBudget

### ISSUE THREAD

**Issue by jmatias** [Comcast/kuberhealthy#628]
**Describe the solution you would like to see happen**

Hi Kuberhealthy team,

Would you be willing to accept a PR that parameterizes the `PodDisruptionBudget`?  Right now, the `minAvailable`  is hardcoded to 1.

**Comment by jonnydawg** [comment]
Yes, we appreciate any contributions to the project!

Please feel free to submit a PR.

**Comment by jmatias** [comment]
@jonnydawg Take a look when you can
