### ISSUE TITLE
Changing daemonset and deployment image is not possible via chart

### ISSUE THREAD

**Issue by erezo9** [Comcast/kuberhealthy#629]
**Describe the bug**
Installing helm chart with a private repo (no access to public internet images)

**Steps To Reproduce**
have an environment with no internet connection and a private repo
**Expected behavior**
Be able to input own private repo image

**Screenshots**
not applicable

**Versions**
 - Cluster OS: [e.g. CoreOS 1800.1.0]
 - Kubernetes Version: 1.17.5
 - Kuberhealthy Release or build [latest release]

**Additional context**
is there anyway doing it via helm chart chaning the nginx or pause image required?

**Comment by jonnydawg** [comment]
Hello, you can change the repository location here in the [values.yaml].(https://github.com/Comcast/kuberhealthy/blob/57240209ec7665a1b9dd8e72deb251234499d184/deploy/helm/kuberhealthy/values.yaml#L70)

Then you should be able to re-create a template using helm!

**Comment by erezo9** [comment]
@jonnydawg not that images, the ones after the deployment and daemon set are deployed

It deployed another deployment with nginx as an image and one with k8s pause image, those I was talking about

**Comment by jonnydawg** [comment]
Those images can be changed via setting environment variables on the two checks.

Here for the deployment check:
https://github.com/Comcast/kuberhealthy/blob/a1df6b7068f8ff17df4e61ee73fd5502d0f9476e/deploy/helm/kuberhealthy/values.yaml#L80

and here for the daemonset check:
https://github.com/Comcast/kuberhealthy/blob/a1df6b7068f8ff17df4e61ee73fd5502d0f9476e/deploy/helm/kuberhealthy/values.yaml#L71

For example, to override the base pause image to `my-pause-image` for the daemonset check, you would need to set the `PAUSE_CONTAINER_IMAGE` environment variable to your image:

Ex: (daemonset-check)
```yaml
extraEnvs:
  PAUSE_CONTAINER_IMAGE: "my-pause-image"
```

The same can be done with the deployment check :
Ex: (deployment-check)
```yaml
extraEnvs:
  CHECK_IMAGE: "my-server-a"
  CHECK_IMAGE_ROLL_TO: "my-server-b"
```

More information about these can be found on the READMEs for the checks -- [daemonset check](https://github.com/Comcast/kuberhealthy/blob/master/cmd/daemonset-check/README.md) & [deployment check](https://github.com/Comcast/kuberhealthy/blob/master/cmd/deployment-check/README.md)

**Comment by erezo9** [comment]
Why not add this to the main readme?
or point that to them either on the main page
dont think its obvious its exists  until u encounter the error - not for me at least

**Comment by jonnydawg** [comment]
That is a valid point! I will look into making this more obvious / linked on the main readme.

**Comment by erezo9** [comment]
@jonnydawg Thanks,I’ll close this issue since the issue is resolved hopefully others will not encounter this issue like me
