### ISSUE TITLE
Test Kuberhealthy 2.3 in lab clusters

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#630]
To prepare for a 2.3 release, we should build and run the newest master code in our environments.

**Comment by jonnydawg** [comment]
Be careful, there's a `v2.3.0` and `v2.3.1-alpha` image that are up on [Docker](https://hub.docker.com/repository/registry-1.docker.io/kuberhealthy/kuberhealthy/tags?page=1)

**Comment by integrii** [comment]
It looks like #648 may be new in this 2.3 release.  We should fix that before a release.

**Comment by integrii** [comment]
Testing of jobs looks great.  We are now testing the check reaper for khjobs to ensure that is stable and both features have been moved up to a 2.3 release instead of a 2.4.
