### ISSUE TITLE
kuberhealthy/deployment error from /metrics have a wrong string format

### ISSUE THREAD

**Issue by darleilopes** [Comcast/kuberhealthy#634]
**Describe the bug**
The check `kuberhealthy/deployment` error is not closing correctly the string at `error` value, were Prometheus can't consuming this metric cause it cannot run parse.
 
**Steps To Reproduce**
Invoking `kuberhealthy/deployment` check producing an error.

**Expected behavior**
Change the metric output `error="deployments.apps is forbidden: User "system:serviceaccount:kuberhealthy:default" cannot create resource "deployments" in API group "apps" in the namespace "kuberhealthy"|"` to, for example `error="deployments.apps is forbidden: User 'system:serviceaccount:kuberhealthy:default' cannot create resource 'deployments' in API group 'apps' in the namespace 'kuberhealthy'|"`, or another format that allow close the string correctly.

**Screenshots**
The `/metrics` endpoint is returning the following output:
```bash
kuberhealthy_check{check="kuberhealthy/deployment",namespace="kuberhealthy",status="0",error="deployments.apps is forbidden: User "system:serviceaccount:kuberhealthy:default" cannot create resource "deployments" in API group "apps" in the namespace "kuberhealthy"|"} 0
```
**Versions**
 - Cluster OS: Debian 10
 - Kubernetes Version: 1.16.6
 - Kuberhealthy Version: 2.2.0

**Comment by integrii** [comment]
Looks like our error metadata needs sanitized so that the prometheus metrics don't become unparsable.  Thanks for bringing this up!  We will look at sanitizing the error messages in our Prometheus metric data.

**Comment by darleilopes** [comment]
One thing I could see is that when this error occurred, my prometheus stopped seeing all metrics, in which I see a risk of losing control of other events due to this error
