### ISSUE TITLE
New Helm Chart Release

### ISSUE THREAD

**Issue by mitchellmaler** [Comcast/kuberhealthy#652]
Currently in the kuberhealthy served repo only chart version 2.2.0 is available but in the charts directory the chart is version 2.2.2. Can the chart be released so that way we can install the newer chart version?

**Comment by integrii** [comment]
We are adding automation here so that our charts are automatically released.  This is blocked on #656 for now...

**Comment by joshulyne** [comment]
@mitchellmaler 2.3.0 is officially out! And we have automated our helm packaging so every time we do a new release https://github.com/Comcast/kuberhealthy/releases, a new helm chart should be available for install!
