### ISSUE TITLE
Improve automation for releases

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#656]
Relevant to #652 

We should ensure the triggers for github actions cause the following workflow:

- Whenever a tag is created, the helm chart `Chart.yaml` should be updated to the matching `appVersion` and the `version` tag for the chart should be updated to any version newer than the current version.  This will be in the form of an automatic PR.
- When the helm chart is modified, a new action should kick off that causes the chart repository to be regenerated (adding the new chart version).  This will cause an automated PR.

**Comment by chadbitzer** [comment]
Still working on the GH action.  Maybe I’m overthinking this but I haven’t been able to get the matching to pick up published version wildcards for github.ref in an if statement.  Also troubleshooting permission denied for the separate .sh files triggered by the if conditional.  the original .sh works fine in their place so trying to understand what the difference is with perms.  If anyone cares to look, the fork is https://github.com/cdbitz/kuberhealthy/actions
