### ISSUE TITLE
Add hard pod anti-affinity to specs

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#68]
We should avoid having multiple Kuberhealthy instances on a single node.  This makes the system prone to failure when a single node is lost.  Pod anti-affinity should take care of this.

**Comment by Brialius** [comment]
@integrii hi, is this request for helm chart?

**Comment by integrii** [comment]
Yeah, and the `deploy/kuberhealthy.yaml` file, which should have the same functionality, but for people who don't want to use helm.
