### ISSUE TITLE
question: does Kuberhealthy prefer to stay away from cluster wide health checks?

### ISSUE THREAD

**Issue by rawlingsj** [Comcast/kuberhealthy#680]
Hi - looking at the existing health checks under https://github.com/Comcast/kuberhealthy/tree/master/cmd all but reaper seem to be namespace scoped.  Is that intentional?

I was wanting to use https://github.com/Comcast/kuberhealthy/tree/master/cmd/pod-status-check and https://github.com/Comcast/kuberhealthy/tree/master/cmd/pod-restarts-check which both take a helm chart value for the namespace to look at, the roles for each service account are then restricted to that namespace.

It would be handy to optionally allow these charts to be cluster wide, maybe installed into the kuberhealthy namespace but have a cluster role that allows the service account to check pods in all namespaces.

As it is today we could install the checks in every namespace we create although it is a little difficult to enforce it and define a set of checks that must always be applied when a namespace is created.

Totally get that its better to stay away from cluster roles but in this case would it be ok and if so would you want a PR to optionally support cluster wide checks for `pod-status` and `pod-restart` which default to single namespace as it is today?

**Comment by rawlingsj** [comment]
fwiw this is the kinda thing I was thinking https://github.com/jenkins-x-plugins/jx-kh-check/pull/5 

for now I've copied the kuberhealthy pod status check and allowed it to be configured to get pods from all namespaces.  We've released it as part of the health Jenkins X chart but happy to PR the changes into this repo if that's something you'd like, totally understand if you prefer your checks to only be namespaced though.

**Comment by integrii** [comment]
We run multi-tenant clusters, so our tilt has been towards namespaced checks.  This way developers in our multi-tenant clusters can write checks without having global permissions.

That said, there isn't anything wrong (imo) with adding an optional parameter to make any existing check run against all namespaces.  It would have to be clear to the user that they would need to use a service account with enough permissions, but it should be fine to add to the project.

The contribution would be great, actually!


I am assuming that something like the below would be added? (from your linked PR)
```
	if namespace == "" {
		// it is the same value but we are being explicit that we are listing pods in all namespaces
		namespace = v1.NamespaceAll
	}
```

**Comment by rawlingsj** [comment]
Great!  Yeah that totally makes sense on the focus of namespaces checks BTW.  

OK so yeah pretty much that line above, maybe an extra log and then probably an extra helm value similar to this 
https://github.com/jenkins-x-plugins/jx-kh-check/blob/1e77a3e3450d62c51dbefe4318f2d7c7ce78abc5/charts/jx-kh-check/values.yaml#L41-L42 

which defaults to `cluster: false` keeping existing behaviour, but if `true` then it would create cluster role and binding like this  https://github.com/jenkins-x-plugins/jx-kh-check/blob/1e77a3e3450d62c51dbefe4318f2d7c7ce78abc5/charts/jx-kh-check/templates/jx-pod-status-check.yaml#L37-L71

I'm happy to pop a PR together tomorrow for pod-status + pod-restarts and see what you think?

**Comment by joshulyne** [comment]
closing issue since we got #681 merged in!
