### ISSUE TITLE
Assigning serviceaccount to deamonset check

### ISSUE THREAD

**Issue by erezo9** [Comcast/kuberhealthy#684]
Is that something thats a available? went through the code, couldnt find anything about it

**Comment by integrii** [comment]
The `serviceAccount` for the daemonset checker pod (the one that builds the daemonset and reports back to kuberhealthy) can be set using the regular pod spec field `serviceAccountName`.  You can set that in the `podSpec` section of the `khcheck`.

As for the `serviceAccount` for the sleep containers that the daemonset check builds, I do not think there is a currently an option for that.  Did you mean to refer to the checker pod's service account or the sleep pod service accounts created by it?

**Comment by erezo9** [comment]
@integrii Hi Thanks for the response
I'm using the helm chart, sorry if I didnt specify that. we want to automaticly install it on ocp clusters, and while we succeed on deploying it, we have an issue that we cant change it from the default service account, unlike the deployment check which does provide this feature
