### ISSUE TITLE
Avoid using generic labels in checks [daemonset-check]

### ISSUE THREAD

**Issue by randrusiak** [Comcast/kuberhealthy#685]
Hi folks!
I started testing kuberhealthy in this week and I like it a lot. 
I have got a small problem with daemonset-check because it using "app" label with ephemeral names of created pods and every day it creates multiple entries in my logging system (grafana loki). 

![image](https://user-images.githubusercontent.com/29524175/96133632-4446c180-0efb-11eb-968f-21f1ef8c0dc9.png)

I think we should avoid using generic labels and instead of use labels for example with a prefix such as "kh_". I've looked at the source code and this label is using only for getting proper pod to delete so renaming shouldn't cause any problems.

**Comment by joshulyne** [comment]
Hey @randrusiak thanks for the feedback! This totally makes sense to change in the daemonset check. Feel free to put up a pr yourself if you'd like to do so :)
