### ISSUE TITLE
security context not compatible with test image

### ISSUE THREAD

**Issue by davidkarlsen** [Comcast/kuberhealthy#689]
**Describe the bug**
The checks fails because the securitycontext is not compatible with the test-image in use:
```
Events:
  Type     Reason          Age                From               Message
  ----     ------          ----               ----               -------
  Normal   Scheduled       86s                default-scheduler  Successfully assigned kuberhealthy/deployment-deployment-c6c86bf77-ls97c to alt-aot-g-kwo02
  Normal   SandboxChanged  84s                kubelet            Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          15s (x9 over 85s)  kubelet            Container image "nginx:1.17.8" already present on machine
  Warning  Failed          15s (x9 over 85s)  kubelet            Error: container has runAsNonRoot and image will run as root
```

**Steps To Reproduce**
- Deploy with default values.

**Expected behavior**
The securityContext in use should be compatible with the container actually run.

**Screenshots**
If applicable, add screenshots to help explain your problem.  You can paste images into github and they will upload automatically.

**Versions**
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9+icp-ee", GitCommit:"fccfecc454d446967475ce34d13d3d63d407bf09", GitTreeState:"clean", BuildDate:"2019-08-27T08:46:50Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
kuberhealthy    kuberhealthy    2               2020-10-17 12:43:39.268047879 +0000 UTC deployed        kuberhealthy-2.2.0      2.2.0      
(2.3.0 is in github but it does not seem to be avail in the helm repo)

**Additional context**

also:

```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  7m6s                   default-scheduler  Successfully assigned kuberhealthy/check-reaper-1602938520-xfb72 to alt-eos-g-kwo04
  Normal   Pulling    7m5s                   kubelet            pulling image "fsdepot.evry.com:8085/kuberhealthy/check-reaper:v1.3.1"
  Normal   Pulled     7m4s                   kubelet            Successfully pulled image "fsdepot.evry.com:8085/kuberhealthy/check-reaper:v1.3.1"
  Warning  Failed     4m45s (x12 over 7m4s)  kubelet            Error: container has runAsNonRoot and image has non-numeric user (user), cannot verify user is non-root
  Normal   Pulled     2m2s (x24 over 7m3s)   kubelet            Container image "fsdepot.evry.com:8085/kuberhealthy/check-reaper:v1.3.1" already present on machine
[et2448@Davids-Work-MacBook-Pro manifests (⎈ |icp-global-context:kuberhealthy)]$ 
```

**Comment by jonnydawg** [comment]
Do you know what tag for the `deployment-check` was being used? Some of the latest changes to the `deployment-check` include moving the default containers to unprivileged containers in #601.

**Comment by davidkarlsen** [comment]
v1.4.4

**Comment by jonnydawg** [comment]
I think the issue here is that the pod is set to `runAsUser: 999`, but the `nginx` image runs as root. You can change the test `nginx` image to any image you'd like via the env vars for the `khc` CRD:
```yaml
      env:
        - name: CHECK_IMAGE
          value: "nginx:1.17-perl"
        - name: CHECK_IMAGE_ROLL_TO
          value: "nginx:1.17.5-perl"
```

**Comment by davidkarlsen** [comment]
I don't think the securityContext is defined for the container - that would override and USER declared in the `Dockerfile`.

**Comment by davidkarlsen** [comment]
OK, moving to the other check image avoids the failing container, but the probes won't pass:
```
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m7s                   default-scheduler  Successfully assigned kuberhealthy/deployment-deployment-7c9bc75dcd-2fhll to alt-eos-g-kwo03
  Normal   Pulling    4m6s                   kubelet            pulling image "fsnexus.evry.com:8085/nginxinc/nginx-unprivileged:1.17.8"
  Normal   Pulled     3m40s                  kubelet            Successfully pulled image "fsnexus.evry.com:8085/nginxinc/nginx-unprivileged:1.17.8"
  Normal   Created    2m28s (x2 over 3m40s)  kubelet            Created container
  Normal   Killing    2m28s                  kubelet            Killing container with id docker://deployment-container:Container failed liveness probe.. Container will be killed and recreated.
  Normal   Pulled     2m28s                  kubelet            Container image "fsnexus.evry.com:8085/nginxinc/nginx-unprivileged:1.17.8" already present on machine
  Normal   Started    2m27s (x2 over 3m40s)  kubelet            Started container
  Warning  Unhealthy  103s (x8 over 3m28s)   kubelet            Liveness probe failed: dial tcp 10.200.105.111:80: connect: connection refused
  Warning  Unhealthy  93s (x9 over 3m33s)    kubelet            Readiness probe failed: dial tcp 10.200.105.111:80: connect: connection refused
```

**Comment by jonnydawg** [comment]
I think this is because the nginx-unprivileged image listens on port `8080` instead of `80`.

You can either set the env variable for the deployment check to use port 8080 or remove it because it will [default to 8080](https://github.com/Comcast/kuberhealthy/tree/master/cmd/deployment-check#check-configuration-environment-variables).
```yaml
        - name: CHECK_CONTAINER_PORT
          value: "8080"
```

**Comment by davidkarlsen** [comment]
yay - that seems to work!
Now to the last problem - there are hundreds of pods in `Complete` status - how can these be automatically cleaned up?

**Comment by jdowni000** [comment]
hey @davidkarlsen , our cronjob check-reaper in kuberhealthy should be able to clean up these completed pods. https://github.com/Comcast/kuberhealthy/tree/master/cmd/check-reaper

**Comment by davidkarlsen** [comment]
doh - now I remember why it was disabled, it has issues with missing securityContext:
```
  ----     ------     ----              ----               -------
  Normal   Scheduled  61s               default-scheduler  Successfully assigned kuberhealthy/check-reaper-1603822860-2jppk to alt-eos-g-kwo04
  Normal   Pulling    61s               kubelet            pulling image "fsnexus.evry.com:8085/kuberhealthy/check-reaper:v1.3.1"
  Normal   Pulled     58s               kubelet            Successfully pulled image "fsnexus.evry.com:8085/kuberhealthy/check-reaper:v1.3.1"
  Warning  Failed     8s (x6 over 58s)  kubelet            Error: container has runAsNonRoot and image has non-numeric user (user), cannot verify user is non-root
  Normal   Pulled     8s (x5 over 58s)  kubelet            Container image "fsnexus.evry.com:8085/kuberhealthy/check-reaper:v1.3.1" already present on machine
```

rendered resource with --debug:
```
# Source: kuberhealthy/templates/check-reaper.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-reaper
  namespace: khtest
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-reaper
              image: fsnexus.evry.com:8085/kuberhealthy/check-reaper:v1.3.1
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          serviceAccountName: check-reaper
  concurrencyPolicy: Forbid
```

I'll check why

**Comment by davidkarlsen** [comment]
the securityContext section of the reaper is not present in the chart version 2.2.0 which is the latest available one via your chart repo at: https://comcast.github.io/kuberhealthy/helm-repos 
Any reason for the repo to not contain the latest versions?

**Comment by jonnydawg** [comment]
We're looking at releasing 2.3.0 within the week. It looks like the next release should address this issue as it was handled in #606

**Comment by jdowni000** [comment]
we just release v2.3.0....this should fix the issue as jonny mentioned above

**Comment by davidkarlsen** [comment]
Thanks - everything works as it should now - thanks a lot.
Maybe running nginx-unprivileged should be considered as a default as it requires less privilegies?
