### ISSUE TITLE
Improve shutdown grace period handling

### ISSUE THREAD

**Issue by lolimjake** [Comcast/kuberhealthy#7]
Kuberhealthy shutdown grace period should be calculated from the running spec instead of being statically configured.

**Comment by lolimjake** [comment]
#134 Exposes the grace period as an env var, we now just need to consume this var and pass it through to the shutdown contexts

**Comment by integrii** [comment]
Line 39 in `main.go` needs overridden when the environment variable for termination grace period seconds is set.  This probably needs done in the `init()` func.

**Comment by lolimjake** [comment]
https://github.com/Comcast/kuberhealthy/blob/master/cmd/kuberhealthy/main.go#L39

**Comment by integrii** [comment]
Looks like we can't actually do this due to the kubernetes downward API not exposing `terminationGracePeriodSeconds`
