### ISSUE TITLE
The `add-path` command is disabled in github actions

### ISSUE THREAD

**Issue by jdowni000** [Comcast/kuberhealthy#727]
New Error from deprecated command using github actions.

`Error: Unable to process command '::add-path::/opt/hostedtoolcache/kind/0.8.1/x64' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/`

see https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

need to update

**Comment by integrii** [comment]
@jonnydawg fixed in #729
