### ISSUE TITLE
Support tolerations for khchecks

### ISSUE THREAD

**Issue by ElectricRabbit** [Comcast/kuberhealthy#728]
I'd like to have option in chart to define tolerations for checks. There are nodeSelectors already, but not tolerations.

We have all production workers tainted so I'm not able to configure checks using chart to use tainted workers.

**Comment by joshulyne** [comment]
That makes sense. Shouldn't be too difficult to do! Feel free to submit a PR for it :D

**Comment by ElectricRabbit** [comment]
> That makes sense. Shouldn't be too difficult to do! Feel free to submit a PR for it :D

I tried to add this configuration to chart and khchecks templates. I'm just testing it, but it seems, operator doesn't understand this configuration. Unfortunately I'm not GO developer. :(
