### ISSUE TITLE
Legacy source URL in Chart.yaml

### ISSUE THREAD

**Issue by TJM** [Comcast/kuberhealthy#736]
**Describe the bug**
Legacy source URL located in Chart.yaml: https://github.com/Comcast/kuberhealthy/blob/48467f5bcab6717e3436a7268b57295fad4f3a05/deploy/helm/kuberhealthy/Chart.yaml#L31

Should probably either be removed or updated to https://github.com/Comcast/kuberhealthy/tree/master/deploy/helm/kuberhealthy

**Steps To Reproduce**
https://artifacthub.io/packages/helm/kuberhealthy/kuberhealthy

**Expected behavior**
Source Links should not point to deprecated source

**Screenshots**
N/A

**Versions**
 - Cluster OS: N/A
 - Kubernetes Version: N/A
 - Kuberhealthy Release or build [e.g. 0.1.5 or 235] 33?

**Additional context**
Stumbled my way in here from the stable chart :)

**Comment by joshulyne** [comment]
@TJM thanks for pointing this out! you're right, it should be `https://github.com/Comcast/kuberhealthy/tree/master/deploy/helm/kuberhealthy` ! 
Feel free to submit a pr for it if you like :)
