### ISSUE TITLE
check-reaper mapped to admin role instead of custom role in tagged version 2.3.1 but fixed in master

### ISSUE THREAD

**Issue by dmildh** [Comcast/kuberhealthy#764]
**Describe the bug**
Fixes within this PR are not tagged on 2.3.1 https://github.com/Comcast/kuberhealthy/pull/737

**Steps To Reproduce**
Deploy chart version 33 (2.3.1)

**Expected behavior**
check-reaper is mapped to a role created for it

**Additional context**
Results in the following error: 
msg="Error: failed to retrieve khjob list with error khjobs.comcast.github.io is forbidden: User \"system:serviceaccount: │
│ namespacename:check-reaper\" cannot list resource \"khjobs\" in API group \"comcast.github.io\" at the cluster scope"

Maybe 2.3.1 can just be re-released with this fix? Thank you.

**Comment by joshulyne** [comment]
I don't believe we do re-releases @integrii(?), but we do need to do a new release soon. It's the holidays for a lot of us rn, but we'll make sure to prioritize a release when we're all back next week! Thanks!

**Comment by integrii** [comment]
Released with v2.3.2 today!
