### ISSUE TITLE
Custom toleration to deployment check 

### ISSUE THREAD

**Issue by igormishsky** [Comcast/kuberhealthy#767]
**Describe the feature you would like and why you want it**
Add way to define custom toleration for deployment check such that also the value can be set (only the key can be set atm).
Also add way to define array of toleration. 
**Additional context**
There is a need to be able to define on what nodes the pods can tolerate.
Right now there is a single value that can be set using the TOLERATION_VALUE env flag which adds to it the value of [kuberhealthy ](https://github.com/Comcast/kuberhealthy/blob/972c1837acc809254fc9d2414394fd251b73fc90/cmd/deployment-check/deployment.go#L262). 
The other issue if that is nothing is set it will tolerate everything including Kubernetes taints ( node.kubernetes.io/unreachable node.kubernetes.io/unschedulable), I think the default behaviour should be to tolerate nothing like it was in the previous versions.

**Comment by integrii** [comment]
@jdowni000 can refactor so that all 3 options in a toleration are able to be specified.  The default behavior should be that no tolerations are in place for the deployment check.

**Comment by jdowni000** [comment]
this is currently being tested. I have created logic to handle multiple tolerations, single tolerations, as well as provide a default action of no tolerations in the event it is left blank (default behavior as it acted before)
