### ISSUE TITLE
Allow overriding env variables in check-reaper 

### ISSUE THREAD

**Issue by AshutoshNirkhe** [Comcast/kuberhealthy#768]
**Describe the feature you would like and why you want it**
Currently env variables used in check reaper template are hard-coded as in,
MAX_PODS_THRESHOLD - https://github.com/Comcast/kuberhealthy/blob/master/deploy/helm/kuberhealthy/templates/check-reaper.yaml#L32
JOB_DELETE_TIME_DURATION - https://github.com/Comcast/kuberhealthy/blob/master/deploy/helm/kuberhealthy/templates/check-reaper.yaml#L34

Some checks (like daemonset check) keeps a lot of pods in Completed state which basically eats IPs. If we could reduce(override) these values, it will be really useful.

**Additional context**
In general, I have observed some hard-coded values (which actually are set through variables in templates in most cases but) not exposed through values.yaml file which makes it a bit to difficult to customize things. I have opened few other issues like #766 , #760 etc. Allowing customizing the checks behaviors wherever possible will make them more usable IMHO. Thanks!

**Comment by AshutoshNirkhe** [comment]
Raised https://github.com/Comcast/kuberhealthy/pull/769

**Comment by joshulyne** [comment]
This makes sense, merged in #769! Closing this issue for now, but will keep your other issue #766! Feel free to submit prs as you see fit! Thank you!! :D
