### ISSUE TITLE
Move check-reaper into main Kuberhealthy binary

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#774]
We should move the check-reaper cronjob directly into Kuberhealthy and run it on a ticker.  This will make the check reaper more reliable, and decreases our chance of a cronjob failing to schedule/run, which results in a pile of completed/running/failed check pods building up.

**Comment by integrii** [comment]
This one is very important but didn't make the 2.4.0 release today.

**Comment by jdowni000** [comment]
this is currently being tested in lab with image `kuberhealthy:reaper`
