### ISSUE TITLE
http-check: not specifying PASSING_PERCENT throws error

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [Comcast/kuberhealthy#780]
**Describe the bug**
http-check results in `"Error converting PASSING_PERCENT to int: strconv.Atoi: parsing \"\": invalid syntax"` when PASSING_PERCENT is not provided as an env var.

**Steps To Reproduce**
- Apply the khcheck manifest for an http-check without specifying the `PASSING_PERCENT` env var.

**Expected behavior**
A default value like 75 or 80 should be automatically set as PASSING_PERCENT if it is not provided as an env var.

**Screenshots**

**Versions**

**Additional context**
It's a very minimal change of adding the following snippet to https://github.com/Comcast/kuberhealthy/blob/master/cmd/http-check/main.go
```go
if len(passing)==0 {
    passing = "100" //or 80 or whatever the default passing percent value
}
```

**Comment by yashvardhan-kukreja** [comment]
@integrii  I already created a PR regarding this fix some days ago and raised. I tested it and it works well.
Can you please take a look at this?
Thanks :)

**Comment by integrii** [comment]
Oh!  We did some review today and didn't see it in your other PR.  We have a release meeting for 2.3 tomorrow. I will be sure we take another look.

**Comment by yashvardhan-kukreja** [comment]
Sure, no worries :)
