### ISSUE TITLE
Helm Install Error CronJob: v1.EnvVar.v1.EnvVar.Value: ReadString: expects " or n, but found 4, error found in #10 byte

### ISSUE THREAD

**Issue by mitchellmaler** [Comcast/kuberhealthy#792]
**Describe the bug**
When helm is rendering the helm chart it is using the number 4 instead of a string for the check reaper cronjob here https://github.com/Comcast/kuberhealthy/blob/master/deploy/helm/kuberhealthy/templates/check-reaper.yaml#L41

`Error: CronJob in version "v1beta1" cannot be handled as a CronJob: v1beta1.CronJob.Spec: v1beta1.CronJobSpec.JobTemplate: v1beta1.JobTemplateSpec.Spec: v1.JobSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.v1.EnvVar.Value: ReadString: expects " or n, but found 4, error found in #10 byte of ...|,"value":4},{"name":|..., bigger context ...|"value":""},{"name":"MAX_PODS_THRESHOLD","value":4},{"name":"JOB_DELETE_TIME_DURATION","value":"15m"|... `

**Expected behavior**
Template wraps 4 with quotes so it is accepted by the api server.

**Versions**
 - Kubernetes Version: v1.19.3
 - Kuberhealthy Release or build [e.g. 0.1.5 or 235]: Chart version 43

**Additional context**

**Comment by integrii** [comment]
This is probably all over the helm chart, but I addressed it with a quick ` | toString` in PR #793.
