### ISSUE TITLE
Kuberhealthy check pods failing with nil pointer error on Ephemeral Kubernetes nodes

### ISSUE THREAD

**Issue by AshutoshNirkhe** [Comcast/kuberhealthy#798]
**Describe the bug**
We are running Kuberhealthy checks (deployment/dns etc) on our AKS(Azure Kubernetes Service) cluster. The check pods were all fine until we started using 'Ephemeral' k8s worker nodes. We have started getting 'panic: runtime error: invalid memory address or nil pointer dereference' error in all check pods that are running on Ephemeral nodes. 
Ref -  https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#ephemeral-os

I am not sure yet what's exactly breaking in the code, but it appears to me around - https://github.com/Comcast/kuberhealthy/blob/v2.3.0/pkg/checks/external/checkclient/main.go#L95 

Error details,

time="2021-01-27T10:44:31Z" level=info msg="Running DNS status checker"
time="2021-01-27T10:44:31Z" level=info msg="DNS Status check testing hostname: kubernetes.default"
time="2021-01-27T10:44:31Z" level=info msg="DNS Status check determined that kubernetes.default was OK."
2021/01/27 10:44:31 checkClient: DEBUG: Reporting SUCCESS
2021/01/27 10:44:31 checkClient: DEBUG: Sending report with error length of:0
2021/01/27 10:44:31 checkClient: DEBUG: Sending report with ok state of:true
2021/01/27 10:44:31 checkClient: INFO: Using kuberhealthy reporting URL:http://kuberhealthy.synthetic.svc.cluster.local/externalCheckStatus
2021/01/27 10:44:31 checkClient: DEBUG: Making POST request to kuberhealthy:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11f1473]
goroutine 1 [running]:
github.com/Comcast/kuberhealthy/v2/pkg/checks/external/checkclient.sendReport(0x202a688, 0x0, 0x0, 0x1, 0xc0005080a8, 0xc0003b3d74)
        /build/pkg/checks/external/checkclient/main.go:99 +0x4e3
github.com/Comcast/kuberhealthy/v2/pkg/checks/external/checkclient.ReportSuccess(0xc0003b3df0, 0xc000508000)
        /build/pkg/checks/external/checkclient/main.go:44 +0x7e
main.reportKHSuccess(0xc0003b3dc8, 0xc0003b3d70)
        /build/cmd/dns-resolution-check/main.go:182 +0x2d
main.(*Checker).Run(0xc000349d20, 0xc000330420, 0xc0003b3ed0, 0x2)
        /build/cmd/dns-resolution-check/main.go:161 +0x204
main.main()
        /build/cmd/dns-resolution-check/main.go:119 +0x3ce

**Steps To Reproduce**
- Create a 'Ephemeral' AKS nodepool.
- Spin Kuberhealthy checks like deployment/dns on 'Ephemeral' nodes.

**Expected behavior**
Expectation was that check pods will continue to run without issues irrespective of k8s worker node os disk type.

**Screenshots**
If applicable, add screenshots to help explain your problem.  You can paste images into github and they will upload automatically.

**Versions**
 - Cluster OS: Ubuntu 18.04.5 LTS
 - Kubernetes Version: AKS v1.18.10

**Additional context**

**Comment by integrii** [comment]
This should be fixed in #765 This should be fixed now from PR #765, but the checks you are using probably haven't had the fixed check client package compiled into them yet...

Leaving this open because we need to rebuild all checks and up their tags.

**Comment by AshutoshNirkhe** [comment]
> This should be fixed in #765 This should be fixed now from PR #765, but the checks you are using probably haven't had the fixed check client package compiled into them yet...
> 
> Leaving this open because we need to rebuild all checks and up their tags.

Thanks @integrii

**Comment by integrii** [comment]
@joshulyne is going to work on these rebuilds soon.

**Comment by joshulyne** [comment]
Addressed in #820!
