### ISSUE TITLE
Unable to install kuberhealthy/check-reaper using helm

### ISSUE THREAD

**Issue by Aqilmirza** [Comcast/kuberhealthy#807]
**Describe the bug**
CheckREaper is failing to install using help

**Steps To Reproduce**
-Using below commands to install kuberhealthy:
helm repo add kuberhealthy https://comcast.github.io/kuberhealthy/helm-repos
helm repo update
helm install kuberhealthy kuberhealthy/kuberhealthy --kubeconfig=kubeconfig --namespace=e2e-test \
     --set check.daemonset.enabled=false,check.deployment.enabled=false,check.dnsInternal.enabled=false

Installation getting failed while installing check-reaper with below error:
Error: CronJob in version "v1beta1" cannot be handled as a CronJob: v1beta1.CronJob.Spec: v1beta1.CronJobSpec.JobTemplate: v1beta1.JobTemplateSpec.Spec: v1.JobSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.v1.EnvVar.Value: ReadString: expects " or n, but found 4, error found in #10 byte of ...|,"value":4},{"name":|..., bigger context ...|"value":""},{"name":"MAX_PODS_THRESHOLD","value":4},{"name":"JOB_DELETE_TIME_DURATION","value":"15m"|...
make: *** [local-test] Error 1

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  You can paste images into github and they will upload automatically.

**Versions**
 - Cluster OS: [e.g. CoreOS 1800.1.0]
 - Kubernetes Version: 1.9.7
 - Kuberhealthy Release or build [e.g. 0.1.5 or 235]

**Additional context**

**Comment by integrii** [comment]
Check reaper is being removed in the next release!  The check-reaper will now be built directly into the main KH binary...  Hold tight for a few more days.

**Comment by djsly** [comment]
@AshutoshNirkhe good to know.. the next chart will remove the reaper... might be good to wait 1-2 days. 
@integrii  looking forward the next release as the reaper has Job is causing us some wasted resources :)

**Comment by integrii** [comment]
We're planning on that release tomorrow!
