### ISSUE TITLE
Using imageRegsitry value messes up the indentation in templates of chart

### ISSUE THREAD

**Issue by AshutoshNirkhe** [Comcast/kuberhealthy#810]
**Describe the bug**
Trying to make use of 'imageRegistry' from values.yaml causes indentation issues in Kuberhealthy chart templates e.g. at
https://github.com/Comcast/kuberhealthy/blob/v2.3.2/deploy/helm/kuberhealthy/templates/check-reaper.yaml#L17

"error converting YAML to JSON: yaml: line 15: did not find expected key :"

Right now we can workaround this by using image.registry under individual components like 'check.deployment.image.registry'

**Steps To Reproduce**
- Have 5,000,000 pods in kube-system.
- Enable restart checking.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  You can paste images into github and they will upload automatically.

**Versions**
 - Cluster OS: [e.g. CoreOS 1800.1.0]
 - Kubernetes Version: 1.9.7
 - Kuberhealthy Release or build v2.3.2
**Additional context**

**Comment by integrii** [comment]
It seems like we just need to delete the `-` on the if conditions that look like this:

This breaks:
```
              image: {{- .Values.imageRegistry }}/{{ .Values.checkReaper.image.repository }}:{{ .Values.checkReaper.image.tag }}
```

This works:
```
              image: {{ .Values.checkReaper.image.registry }}/{{ .Values.checkReaper.image.repository }}:{{ .Values.checkReaper.image.tag }}
```

**Comment by AshutoshNirkhe** [comment]
> It seems like we just need to delete the `-` on the if conditions that look like this:
> 
> This breaks:
> 
> ```
>               image: {{- .Values.imageRegistry }}/{{ .Values.checkReaper.image.repository }}:{{ .Values.checkReaper.image.tag }}
> ```
> 
> This works:
> 
> ```
>               image: {{ .Values.checkReaper.image.registry }}/{{ .Values.checkReaper.image.repository }}:{{ .Values.checkReaper.image.tag }}
> ```

Thanks, yeah exactly!
