### ISSUE TITLE
Checker pods do not get cleaned up.

### ISSUE THREAD

**Issue by talonx** [Comcast/kuberhealthy#855]
**Describe the bug**
Checker pods are not deleted after they complete. They hang around forever.

**Steps To Reproduce**
- Deploy the helm chart to install kuberhealthy.

**Expected behavior**
Pods to be cleared after they are completed.

**Screenshots**
NA. See the gist for the list of pods.
https://gist.github.com/talonx/662f3a8e98018fb5078093be7190f5bc

**Versions**
 - Cluster OS: [GKE]
 - Kubernetes Version: 1.16
 - Kuberhealthy Release or build - latest from master (5c8da01d1ef853c63b7a815d896373fbfed21a87)

**Additional context**

**Comment by integrii** [comment]
Are you using the latest helm chart?  In the logs that you supplied, I see the old check-reaper cron job still running, which was removed in favor of putting the reaper directly into the main Kuberhealthy binary.

```
check-reaper-1614185640-rvhr8    0/1     Completed   0          8m23s
check-reaper-1614185820-hdgmg    0/1     Completed   0          5m23s
check-reaper-1614186000-z7ctq    0/1     Completed   0          2m22s
```

Also, you might have a permissions issue... Can you check the logs on the Kuberhealthy master (the first one in the `kubectl get pods` list) as well as the logs on those `check-reaper` pods?

**Comment by talonx** [comment]
Indeed, I was using an older chart. When I upgraded I don't see the problem any more. However, the reaper jobs still show as running but I can see completed pods getting removed.

**Comment by jdowni000** [comment]
If you have upgraded the chart, check the kuberhealthy logs and grep checkReaper. The main binary of kuberhealthy now is removing the pods and the cronjob itself may not be needed anymore as this was our intention to move away from cronjobs that may become unavailable for multiple reasons.

**Comment by integrii** [comment]
I am going to close this one because it sounds like its working.  It may be that the new version of the chart isn't removing the check reaper for some reason.  If that is true, we should see if anyone else confirms the issue.
