### ISSUE TITLE
When the value of  khchecks' runInterval  field is a little small, the khcheck pod  can't enter the "Running" state, and will be deleted forcely under a certain probability, which will report an error to the khstate object.

### ISSUE THREAD

**Issue by harryyann** [Comcast/kuberhealthy#894]
When I deploy a kuberhealthy in my cluster, I set several khchecks which the runInterval field set to 5min or 10min. In the very beginning of time, it runs well. But suddenly I got a lot of errors from the kuberhealthy report. The error is almost "pod deleted unexpectedly". So I keep monitor the khcheck pod. I found that every time the khcheck pod will stay in "ContainerCreating" status for more than 1 min，and then the pod will be deleted forcely. But my khcheck pod usually takes about ten seconds to enter the "Running" state, and run about 1 min it will be Completed which is much less than the runInterval. The weird thing is that I discover when the khcheck pod is stay in "ContainerCreating" status, the code in the pod is start running! I was really puzzled. Because the pod cannot enter the "Running"  status, so I can't get logs of the pod. I don't know why. Then I tried to set the runInterval to 20 min, the errors' gone! I am very puzzled why this happen. The k8s cluster should be no problem. I really hope to get your help. Thank you very much.

**Comment by integrii** [comment]
Thanks for your report.

- Can you run `kubectl describe` on the pod that is stuck in `ContainerCreating`?  It would be helpful to see the `Events` section.
- Can you paste your `khcheck` here so we can review?
- Can you find logs from your `kuberhealthy` pod around the time when it says `pod deleted unexpectedly`?
