### ISSUE TITLE
khcheck-storage fails due to template issues

### ISSUE THREAD

**Issue by blame19** [Comcast/kuberhealthy#895]
**Describe the bug**
I'm trying to set up kuberhealthy with the khcheck-storage template, but I'm running into yaml formatting issues:

`Error: template: kuberhealthy/templates/khcheck-storage.yaml:21:20: executing "kuberhealthy/templates/khcheck-storage.yaml" at <.Values.imageRegistry>: can't evaluate field Values in type interface {}`

**Steps To Reproduce**
- Setup kuberhealthy with the checks.storage section

**Expected behavior**
Kuberhealthy would deploy with all the defined checks in place.

**Versions**
 - Cluster OS: [e.g. CoreOS 1800.1.0]
 - Kubernetes Version: 1.18.14
 - Kuberhealthy Release or build v2.4.1

**Comment by integrii** [comment]
Hrmm.. Kubernetes 1.8 seems pretty old... That worries me a little bit because CRDs were pretty new then.

However, we should try to get a reproduction of this issue to be sure its not a problem with the chart... Were you rendering the template with Helm?  What version of Helm?

**Comment by blame19** [comment]
Sorry, my bad. I meant  1.18.14, edited the main issue. And yes, I was deploying it with helm

**Comment by joshulyne** [comment]
@blame19 thanks so much for the fix! 🎉
