### ISSUE TITLE
Implement a persistent volume checker

### ISSUE THREAD

**Issue by lolimjake** [Comcast/kuberhealthy#9]
We need a way to confirm that PVCs and PVs can be requested and attached to every node in a cluster. We probably want to leverage the DaemonSet checker for this and have this be a configurable option.

**Comment by integrii** [comment]
Today we had an issue in production where a node ceased to be able to provision more volumes.  This could have detected the issue.

**Comment by joshulyne** [comment]
Closing this as we now have a storage check that does exactly this: https://github.com/ChrisHirsch/kuberhealthy-storage-check
