### ISSUE TITLE
How should I run khcheck with hostNetwork=true ?

### ISSUE THREAD

**Issue by harryyann** [Comcast/kuberhealthy#901]
I wrote a khcheck instance and run it in my cluster. And I set `hostNetwork=true` in the "podSpec" field. I know that I can't use the checkclient pkg because the report method use the clusterIp of kuberhealthy svc. So I write a new report method just send a POST request to the report url.  But I found the pod of my khcheck can't send report to the kuberhealthy control plane. The logs are below:

```
I0426 09:39:10.449461     181 main.go:392] Reporting SUCCESS
I0426 09:39:10.449545     181 main.go:425] DEBUG: Making POST request to kuberhealthy report url: http://10.212.214.177:80/externalCheckStatus
E0426 09:40:10.877513     181 main.go:436] ERROR: got a bad status code from kuberhealthy:%!(EXTRA int=400, string=400 Bad Request)
E0426 09:40:10.877552     181 main.go:396] Error reporting success to Kuberhealthy servers:bad status code from kuberhealthy status reporting url: [400] 400 Bad Request 
E0426 09:40:10.877563     181 main.go:164] Error running ncr check, err: bad status code from kuberhealthy status reporting url: [400] 400 Bad Request 
```
the code of report method is:
```
func sendReport (newReport status.Report)error{
	b, err := json.Marshal(newReport)
	if err != nil{
		return err
	}

	// send to the server
	exponentialBackoff := backoff.NewExponentialBackOff()
	exponentialBackoff.MaxElapsedTime = time.Second * 30
	var resp *http.Response
	err = backoff.Retry(func() error {
		var err error
		klog.Infof("DEBUG: Making POST request to kuberhealthy report url: %s", reportUrl)
		resp, err = http.Post(reportUrl, "application/json", bytes.NewBuffer(b))
		return err
	}, exponentialBackoff)
	if err != nil {
		klog.Errorf("ERROR: got an error sending POST to kuberhealthy:", err.Error())
		return fmt.Errorf("bad POST request to kuberhealthy status reporting url: %w", err)
	}

	// make sure we got a 200 and consider it an error otherwise
	if resp.StatusCode != http.StatusOK {
		klog.Errorf("ERROR: got a bad status code from kuberhealthy:", resp.StatusCode, resp.Status)
		return fmt.Errorf("bad status code from kuberhealthy status reporting url: [%d] %s ", resp.StatusCode, resp.Status)
	}
	return nil
}
```

what should I do?

**Comment by integrii** [comment]
Good timing, actually!  We are just working through a pull request that will remove source IP validation in favor of a header validation process.  Check out PR #884's description.  When this PR merges, you will need to update your `checkClient` package with `go get -u github.com/comcast/kuberhealthy/pkg/checks/external/checkclient` and rebuild your check container so that the new header is used when your check sends its report.

**Comment by harryyann** [comment]
Thank you very much about the reply. But could you give me some quick solutions to my current problem? When I set my khcheck `hostNetwork=true`, the pod's ip is the same with the node's ip. I don't understand why it can't be validated.
